import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    'Pancaran Lelang': 'PLATINUM',
    'Katalog Eksternal': 'Katalog Eksternal',
    'Katalog Eksternal (Public)': 'Katalog Eksternal (Publik)',
    'Area Admin Internal': 'Area Admin Internal',
    'Login Admin': 'Login Admin',
    'Logout Admin': 'Keluar Admin',
    'Admin Active': 'Admin Aktif',
    'Keluar': 'Keluar',
    'Pilih Tampilan': 'Pilih Tampilan',
    'Menu Admin': 'Menu Admin',
    'Dashboard Ringkasan': 'Dashboard Ringkasan',
    'Kelola Aset (Tambah & Bids)': 'Kelola Aset (Tambah & Bids)',
    'Manajemen Akses': 'Manajemen Akses',
    'Setelan Sistem': 'Setelan Sistem',
    'Status Koneksi': 'Status Koneksi',
    'Google Spreadsheet': 'Google Spreadsheet',
    'Sinkronisasi otomatis aktif per detik. Klik tombol di bawah untuk paksa sinkronisasi sekarang.': 'Sinkronisasi otomatis aktif per detik. Klik tombol di bawah untuk paksa sinkronisasi sekarang.',
    'Menyinkronkan...': 'Menyinkronkan...',
    'Sinkronisasi Manual': 'Sinkronisasi Manual',
    'Sedang menyinkronkan...': 'Sedang menyinkronkan...',
    'Berhasil disinkronkan!': 'Berhasil disinkronkan!',
    'Gagal sinkronisasi.': 'Gagal sinkronisasi.',
    'Spreadsheet Sync': 'Spreadsheet Sync',
    'Sync Spreadsheet': 'Sync Spreadsheet',
    'Sinkronisasi Google Spreadsheet berhasil diselesaikan.': 'Sinkronisasi Google Spreadsheet berhasil diselesaikan.',
    'Gagal sinkronisasi dengan Google Spreadsheet.': 'Gagal sinkronisasi dengan Google Spreadsheet.',
    'Lelang Aktif': 'Lelang Aktif',
    'Sedang Berjalan': 'Sedang Berjalan',
    'Unit Terjual': 'Unit Terjual',
    'Otorisasi Diperlukan': 'Otorisasi Diperlukan',
    'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.': 'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.',
    'Masuk Sekarang': 'Masuk Sekarang',
    'Hak Cipta Dilindungi': 'Hak Cipta Dilindungi',
    'Pool Marunda': 'Pool Marunda',
    'Pool Cakung': 'Pool Cakung',
    'Pool Teluk Gong': 'Pool Teluk Gong',
    'Cilincing': 'Cilincing',
    'Admin Digital Solution': 'Admin Digital Solution',
    'AKUN MASUK:': 'AKUN MASUK:',
    'COMPANY INFO': 'INFORMASI PERUSAHAAN',
    'Our Office': 'Kantor Kami',
    'Head Office 1 :': 'Kantor Pusat 1 :',
    'HUBUNGI KAMI': 'HUBUNGI KAMI',
    'Lokasi Pool Inspeksi:': 'Lokasi Pool Inspeksi:',
    'Portal resmi likuidasi armada aktif dan alat berat dari ekosistem operasional Pancaran Group. Transparan, tepercaya, dan terintegrasi.': 'Portal resmi likuidasi armada aktif dan alat berat dari ekosistem operasional Pancaran Group. Transparan, tepercaya, dan terintegrasi.',
    'Syarat & Ketentuan': 'Syarat & Ketentuan',
    'Kebijakan Privasi': 'Kebijakan Privasi',
    'Cari aset lelang...': 'Cari aset lelang...',
    'Merek': 'Merek',
    'Kategori': 'Kategori',
    'Kondisi': 'Kondisi',
    'Lokasi': 'Lokasi',
    'Semua Merek': 'Semua Merek',
    'Semua Kategori': 'Semua Kategori',
    'Semua Kondisi': 'Semua Kondisi',
    'Semua Lokasi': 'Semua Lokasi',
    'Menampilkan {count} aset yang memenuhi kriteria': 'Menampilkan {count} aset yang memenuhi kriteria',
    'Terbuka': 'Terbuka',
    'Terjual': 'Terjual',
    'Th': 'Th',
    'Plat': 'Plat',
    'Harga Awal': 'Harga Awal',
    'Harga Pembuka': 'Harga Pembuka',
    'Penawaran Tertinggi': 'Penawaran Tertinggi',
    'Penawaran Tertinggi:': 'Penawaran Tertinggi:',
    'Belum ada penawaran': 'Belum ada penawaran',
    'Penawaran': 'Penawaran',
    'Penawaran Masuk': 'Penawaran Masuk',
    'Tawar Aset': 'Tawar Aset',
    'Brand:': 'Brand:',
    'Kategori:': 'Kategori:',
    'Tahun:': 'Tahun:',
    'No. Polisi:': 'No. Polisi:',
    'Kondisi:': 'Kondisi:',
    'Lokasi:': 'Lokasi:',
    'Lihat Detail': 'Lihat Detail',
    'Lihat Detail & Ajukan Bid': 'Lihat Detail & Ajukan Bid',
    'Detail Unit Lelang': 'Detail Unit Lelang',
    'Kembali ke Katalog': 'Kembali ke Katalog',
    'Spesifikasi Unit': 'Spesifikasi Unit',
    'Tahun Pembuatan': 'Tahun Pembuatan',
    'Nomor Polisi': 'Nomor Polisi',
    'Kondisi Fisik': 'Kondisi Fisik',
    'Deskripsi Tambahan': 'Deskripsi Tambahan',
    'Informasi & Tata Cara Lelang': 'Informasi & Tata Cara Lelang',
    'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.': 'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.',
    'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.': 'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.',
    'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.': 'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.',
    'Riwayat Penawaran Saat Ini': 'Riwayat Penawaran Saat Ini',
    'Nama': 'Nama',
    'Nilai Bid': 'Nilai Bid',
    'Waktu': 'Waktu',
    'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!': 'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!',
    'Formulir Pengajuan Bid Resmi': 'Formulir Pengajuan Bid Resmi',
    'Masukkan nama lengkap Anda...': 'Masukkan nama lengkap Anda...',
    'Contoh: 08123456789': 'Contoh: 08123456789',
    'Masukkan alamat email aktif...': 'Masukkan alamat email aktif...',
    'Rencana Tanggal Survey': 'Rencana Tanggal Survey',
    'Rencana Jam Survey': 'Rencana Jam Survey',
    'Harga Penawaran Anda (Rupiah)': 'Harga Penawaran Anda (Rupiah)',
    'Min. Penawaran Berikutnya:': 'Min. Penawaran Berikutnya:',
    'Kirim Penawaran & Jadwalkan Survey': 'Kirim Penawaran & Jadwalkan Survey',
    'Memproses...': 'Memproses...',
    'Silakan isi semua data dengan benar.': 'Silakan isi semua data dengan benar.',
    'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!': 'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!',
    'Penawaran Anda Berhasil Dikirim!': 'Penawaran Anda Berhasil Dikirim!',
    'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.': 'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.',
    'Tutup': 'Tutup',
    'Pemenang Lelang': 'Pemenang Lelang',
    'Pemenang': 'Pemenang',
    'Penawaran Pemenang': 'Penawaran Pemenang',
    'Kontak Pemenang': 'Kontak Pemenang',
    'Belum ada penawar': 'Belum ada penawar',
    'Perkecil': 'Perkecil',
    'Perbesar / Fokus Detail': 'Perbesar / Fokus Detail',
    'Seret/Scroll untuk melihat bagian gambar • Klik gambar untuk mengecilkan': 'Seret/Scroll untuk melihat bagian gambar • Klik gambar untuk mengecilkan',
    'Klik gambar atau tombol untuk memperbesar penuh & jelas': 'Klik gambar atau tombol untuk memperbesar penuh & jelas',
    'Sudah Dibooking': 'Sudah Dibooking',
    'Pilih Tanggal Kunjungan': 'Pilih Tanggal Kunjungan',
    'Pilih Sesi Jam Kunjungan': 'Pilih Sesi Jam Kunjungan',
    'Ready': 'Ready',
    'Selected': 'Selected',
    'Booked': 'Booked',
    'Sesi Pagi I': 'Sesi Pagi I',
    'Sesi Pagi II': 'Sesi Pagi II',
    'Sesi Siang I': 'Sesi Siang I',
    'Sesi Sore II': 'Sesi Sore II',
    'Informasi Lokasi & Pendampingan': 'Informasi Lokasi & Pendampingan',
    'Jadwal survei pada tanggal dan jam tersebut sudah di-booking oleh calon pembeli lain. Mohon pilih waktu atau hari lain.': 'Jadwal survei pada tanggal dan jam tersebut sudah di-booking oleh calon pembeli lain. Mohon pilih waktu atau hari lain.',
    'Klik gambar untuk berikutnya • Klik di luar untuk kembali': 'Klik gambar untuk berikutnya • Klik di luar untuk kembali',
    'Klik gambar atau di luar untuk kembali': 'Klik gambar atau di luar untuk kembali',
    'Klik gambar untuk memperkecil • Geser untuk menjelajah detail': 'Klik gambar untuk memperkecil • Geser untuk menjelajah detail',
    'Klik gambar untuk memperbesar • Klik di luar untuk kembali': 'Klik gambar untuk memperbesar • Klik di luar untuk kembali',
    'Zoom In': 'Zoom In',
    'Zoom Out': 'Zoom Out',
    'Otoritas Internal Admin': 'Otoritas Internal Admin',
    'Gunakan email & password terdaftar untuk mengelola sistem lelang.': 'Gunakan email & password terdaftar untuk mengelola sistem lelang.',
    'Email atau password salah. Pastikan kredensial benar.': 'Email atau password salah. Pastikan kredensial benar.',
    'ALAMAT EMAIL KERJA': 'ALAMAT EMAIL KERJA',
    'KATA SANDI (PASSWORD)': 'KATA SANDI (PASSWORD)',
    'Masuk Aplikasi': 'Masuk Aplikasi',
    'Petunjuk Akun Penguji:': 'Petunjuk Akun Penguji:',
    'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.': 'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.',
    'Isi Kredensial Penguji': 'Isi Kredensial Penguji',
    'Dashboard Utama & Analitik': 'Dashboard Utama & Analitik',
    'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.': 'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.',
    'Total Asset': 'Total Aset',
    'Unit di Database': 'Unit di Database',
    'Sedang Aktif': 'Sedang Aktif',
    'Menerima Penawaran': 'Menerima Penawaran',
    'Aset Terjual': 'Aset Terjual',
    'Sudah Diproses': 'Sudah Diproses',
    'Total Bidder': 'Total Penawar',
    'Telah Berpartisipasi': 'Telah Berpartisipasi',
    'Aset Terpopuler': 'Aset Terpopuler',
    'Dengan Penawaran Terbanyak': 'Dengan Penawaran Terbanyak',
    'Daftar Aktivitas Bid Terbaru': 'Daftar Aktivitas Bid Terbaru',
    'Aktivitas Terbaru': 'Aktivitas Terbaru',
    'Daftar pengajuan penawaran harga dari calon pembeli eksternal.': 'Daftar pengajuan penawaran harga dari calon pembeli eksternal.',
    'Semua Riwayat': 'Semua Riwayat',
    'Aset': 'Aset',
    'Penawar': 'Penawar',
    'Jumlah Penawaran': 'Jumlah Penawaran',
    'Tanggal & Waktu': 'Tanggal & Waktu',
    'Status': 'Status',
    'Tindakan': 'Tindakan',
    'Belum ada aktivitas penawaran yang terdaftar di sistem.': 'Belum ada aktivitas penawaran yang terdaftar di sistem.',
    'Lihat Detail Aset': 'Lihat Detail Aset',
    'Daftar Manajemen Aset': 'Daftar Manajemen Aset',
    'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.': 'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.',
    'Tambah Unit Baru': 'Tambah Unit Baru',
    'Daftarkan Aset Lelang Baru': 'Daftarkan Aset Lelang Baru',
    'Lengkapi spesifikasi teknis dan detail dokumen kendaraan di bawah.': 'Lengkapi spesifikasi teknis dan detail dokumen kendaraan di bawah.',
    'Ubah Detail Unit': 'Ubah Detail Unit',
    'Perbarui spesifikasi teknis dan kelengkapan dokumen kendaraan lelang.': 'Perbarui spesifikasi teknis dan kelengkapan dokumen kendaraan lelang.',
    'Semua Aset': 'Semua Aset',
    'Aktif / Open': 'Aktif / Open',
    'Terjual / Sold': 'Terjual / Sold',
    'Cari aset...': 'Cari aset...',
    'Tipe': 'Tipe',
    'Aksi': 'Aksi',
    'Belum ada aset lelang yang cocok dengan pencarian Anda.': 'Belum ada aset lelang yang cocok dengan pencarian Anda.',
    'PILIH TEMPLATE KENDARAAN (OPSIONAL)': 'PILIH TEMPLATE KENDARAAN (OPSIONAL)',
    'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.': 'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.',
    'FORMULIR MANAJEMEN UNIT ASET': 'FORMULIR MANAJEMEN UNIT ASET',
    'Nama Kendaraan / Aset': 'Nama Kendaraan / Aset',
    'Merek / Brand': 'Merek / Brand',
    'Kategori Kendaraan': 'Kategori Kendaraan',
    'Tahun': 'Tahun',
    'Nomor Registrasi (Plat)': 'Nomor Registrasi (Plat)',
    'Sangat Baik': 'Sangat Baik',
    'Baik': 'Baik',
    'Cukup': 'Cukup',
    'Butuh Perbaikan': 'Butuh Perbaikan',
    'Lokasi Pool': 'Lokasi Pool',
    'Harga Awal (IDR)': 'Harga Awal (IDR)',
    'Deskripsi & Spesifikasi Tambahan': 'Deskripsi & Spesifikasi Tambahan',
    'Batal': 'Batal',
    'Simpan Perubahan': 'Simpan Perubahan',
    'Tambah Unit ke Sistem': 'Tambah Unit ke Sistem',
    'Unggah Foto Unit': 'Unggah Foto Unit',
    'Klik untuk unggah atau seret foto ke sini': 'Klik untuk unggah atau seret foto ke sini',
    'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.': 'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.',
    'Foto berhasil diunggah': 'Foto berhasil diunggah',
    'Hapus Foto': 'Hapus Foto',
    'Gambar Utama': 'Gambar Utama',
    'PILIH ALAT BANTU': 'PILIH ALAT BANTU',
    'Dapatkan Saran Deskripsi dengan AI': 'Dapatkan Saran Deskripsi dengan AI',
    'Saran Deskripsi': 'Saran Deskripsi',
    'Gunakan Saran AI': 'Gunakan Saran AI',
    'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.': 'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.',
    'Detail Histori Penawaran': 'Detail Histori Penawaran',
    'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.': 'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.',
    'Detail Spesifikasi': 'Detail Spesifikasi',
    'Histori Bid': 'Histori Bid',
    'Ubah Atribut': 'Ubah Atribut',
    'Ubah Status': 'Ubah Status',
    'Buka Penawaran': 'Buka Penawaran',
    'Tutup / Selesaikan (Sold)': 'Tutup / Selesaikan (Sold)',
    'Hapus Unit': 'Hapus Unit',
    'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?': 'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?',
    'Ya, Hapus': 'Ya, Hapus',
    'Tidak': 'Tidak',
    'Rencana Survey:': 'Rencana Survey:',
    'Belum ada penawaran untuk unit ini.': 'Belum ada penawaran untuk unit ini.',
    'Bids Masuk': 'Bids Masuk',
    'Hubungi': 'Hubungi',
    'PLAT NOMOR': 'PLAT NOMOR',
    'TAHUN PRODUKSI': 'TAHUN PRODUKSI',
    'KONDISI FISIK': 'KONDISI FISIK',
    'LOKASI SEEDING': 'LOKASI SEEDING',
    'DESKRIPSI INTERNAL': 'DESKRIPSI INTERNAL',
    'Histori Penawaran': 'Histori Penawaran',
    'Bids Tertinggi Pertama': 'Bids Tertinggi Pertama',
    'Jadwal Survei': 'Jadwal Survei',
    'Belum ada penawaran harga masuk untuk aset ini.': 'Belum ada penawaran harga masuk untuk aset ini.',
    'Konfirmasi Hapus Unit': 'Konfirmasi Hapus Unit',
    'Edit Unit Aset': 'Edit Unit Aset',
    'Hapus Unit Aset': 'Hapus Unit Aset',
    'Tutup Detail': 'Tutup Detail',
    'Status Lelang Saat Ini:': 'Status Lelang Saat Ini:',
    'Menerima Bid': 'Menerima Bid',
    'Buka Bid': 'Buka Bid',
    'Set Terjual': 'Set Terjual',
    'Sebelumnya': 'Sebelumnya',
    'Berikutnya': 'Berikutnya',
    'Tambah': 'Tambah',
    'Ketik atau tempel tautan gambar, lalu tekan tombol "Tambah" atau Enter untuk memasukkan ke galeri unit lelang ini.': 'Ketik atau tempel tautan gambar, lalu tekan tombol "Tambah" atau Enter untuk memasukkan ke galeri unit lelang ini.',
    'Simpan Unit Baru': 'Simpan Unit Baru',
    'Kelola Aset Lelang': 'Kelola Aset Lelang',
    'Daftarkan armada logistik baru, pantau status lelang, dan verifikasi riwayat penawaran.': 'Daftarkan armada logistik baru, pantau status lelang, dan verifikasi riwayat penawaran.',
    'Tambah Aset Baru': 'Tambah Aset Baru',
    'Cari berdasarkan nama aset, plat, kategori...': 'Cari berdasarkan nama aset, plat, kategori...',
    'Semua Brand': 'Semua Brand',
    'Tidak ada aset lelang yang cocok dengan kriteria pencarian.': 'Tidak ada aset lelang yang cocok dengan kriteria pencarian.',
    'Reset Semua Filter': 'Reset Semua Filter',
    'Merek (Brand) *': 'Merek (Brand) *',
    'Kategori Unit *': 'Kategori Unit *',
    'Dimensi Unit': 'Dimensi Unit',
    'Dimensi Unit (Opsional)': 'Dimensi Unit (Opsional)',
    'Model': 'Model',
    'Series': 'Seri',
    'Axels': 'Axels',
    'Warna Kendaraan': 'Warna Kendaraan',
    'Bahan Bakar': 'Bahan Bakar',
    'Horsepower (HP)': 'Horsepower (HP)',
    'KM Spidometer': 'KM Spidometer',
    'Memiliki Attachment?': 'Memiliki Attachment?',
    'Attachment': 'Attachment',
    'Detail Attachment': 'Detail Attachment',
    'Unggah Attachment': 'Unggah Attachment',
    'Nomor KEUR': 'Nomor KEUR',
    'Berlaku Hingga': 'Berlaku Hingga',
    'Panjang Total (Meter)': 'Panjang Total (Meter)',
    'Lebar Total (TON)': 'Lebar Total (TON)',
    'Tinggi Total (Meter)': 'Tinggi Total (Meter)',
    'Ekstensi': 'Ekstensi',
    'Dimensi': 'Dimensi',
    'Tahun Produksi *': 'Tahun Produksi *',
    'No. Registrasi / Plat Nomor': 'No. Registrasi / Plat Nomor',
    'Kondisi Fisik Unit *': 'Kondisi Fisik Unit *',
    'Harga Awal Lelang (IDR) *': 'Harga Awal Lelang (IDR) *',
    'Lokasi Pool / Depo Unit *': 'Lokasi Pool / Depo Unit *',
    'Foto / Gambar Unit * (Bisa Unggah Banyak)': 'Foto / Gambar Unit * (Bisa Unggah Banyak)',
    'Pilih atau Seret Foto-Foto Armada': 'Pilih atau Seret Foto-Foto Armada',
    'Mendukung format PNG, JPG, JPEG (Bisa pilih banyak sekaligus, Max 5MB per file)': 'Mendukung format PNG, JPG, JPEG (Bisa pilih banyak sekaligus, Max 5MB per file)',
    'Koleksi Foto Terunggah ({count})': 'Koleksi Foto Terunggah ({count})',
    'Cover Utama': 'Cover Utama',
    'Tambah Foto via Tautan Gambar (URL)': 'Tambah Foto via Tautan Gambar (URL)',
    'Apakah Anda yakin ingin menghapus {name} secara permanen? Data historis penawaran juga akan ikut terhapus.': 'Apakah Anda yakin ingin menghapus {name} secara permanen? Data historis penawaran juga akan ikut terhapus.',
    'Akses Internal': 'Akses Internal',
    'Total Akses Internal': 'Total Akses Internal',
    'Total Akses Eksternal': 'Total Akses Eksternal',
    'Administrator Aktif': 'Administrator Aktif',
    'Pengguna Terdaftar': 'Pengguna Terdaftar',
    'Kelola Hak Akses Admin': 'Kelola Hak Akses Admin',
    'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.': 'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.',
    'Daftarkan Admin Baru': 'Daftarkan Admin Baru',
    'Nama Lengkap': 'Nama Lengkap',
    'Alamat Email Pancaran': 'Alamat Email Pancaran',
    'Peran / Hak Akses': 'Peran / Hak Akses',
    'Super Admin': 'Super Admin',
    'Akses Eksternal': 'Akses Eksternal',
    'Admin Operasional': 'Admin Operasional',
    'Admin Keuangan': 'Admin Keuangan',
    'Daftarkan': 'Daftarkan',
    'Akun Terdaftar': 'Akun Terdaftar',
    'Peran': 'Peran',
    'Bergabung': 'Bergabung',
    'Anda': 'Anda',
    'Hapus Akses': 'Hapus Akses',
    'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?': 'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?',
    'Manajemen Akses Admin': 'Manajemen Akses Admin',
    'Buat akses administrator baru, tinjau tingkatan hak akses, dan kelola otoritas keamanan internal Pancaran Lelang.': 'Buat akses administrator baru, tinjau tingkatan hak akses, dan kelola otoritas keamanan internal Pancaran Lelang.',
    'Buat Akses Baru': 'Buat Akses Baru',
    'Daftarkan akun email karyawan baru untuk memberikan akses masuk ke dashboard internal.': 'Daftarkan akun email karyawan baru untuk memberikan akses masuk ke dashboard internal.',
    'Nama Lengkap Admin': 'Nama Lengkap Admin',
    'Contoh: Achmad Subagja': 'Contoh: Achmad Subagja',
    'Harus berupa email institusi Pancaran.': 'Harus berupa email institusi Pancaran.',
    'Tingkatan Peran (Role)': 'Tingkatan Peran (Role)',
    'Admin Operasional (Input & Kelola Aset)': 'Admin Operasional (Input & Kelola Aset)',
    'Admin Keuangan (Otorisasi Unit Terjual)': 'Admin Keuangan (Otorisasi Unit Terjual)',
    'Super Admin (Akses Penuh)': 'Super Admin (Akses Penuh)',
    'Akses Eksternal (Catalog Only)': 'Akses Eksternal (Katalog Saja)',
    'Buat Hak Akses': 'Buat Hak Akses',
    'Daftar Administrator Terdaftar': 'Daftar Administrator Terdaftar',
    'Daftar staf internal Pancaran Logistics yang memegang otoritas sistem Lelang.': 'Daftar staf internal Pancaran Logistics yang memegang otoritas sistem Lelang.',
    'Nama / Karyawan': 'Nama / Karyawan',
    'Email Akun': 'Email Akun',
    'Terdaftar Pada': 'Terdaftar Pada',
    'Ya': 'Ya',
    'Mohon lengkapi nama dan email admin.': 'Mohon lengkapi nama dan email admin.',
    'Email admin tersebut sudah terdaftar.': 'Email admin tersebut sudah terdaftar.',
    'Format email tidak valid. Direkomendasikan menggunakan email institusi Pancaran.': 'Format email tidak valid. Direkomendasikan menggunakan email institusi Pancaran.',
    'Akses admin berhasil dibuat untuk': 'Akses admin berhasil dibuat untuk',
    'Anda sedang masuk dengan akun ini': 'Anda sedang masuk dengan akun ini',
    'Akun Super Admin Utama tidak bisa dihapus': 'Akun Super Admin Utama tidak bisa dihapus',
    'Kelola otentikasi staf internal dan persetujuan registrasi akses lelang untuk pihak eksternal.': 'Kelola otentikasi staf internal dan persetujuan registrasi akses lelang untuk pihak eksternal.',
    'Akses Admin Internal': 'Akses Admin Internal',
    'Akses User Eksternal': 'Akses User Eksternal',
    'Mohon lengkapi nama, email, dan kata sandi admin.': 'Mohon lengkapi nama, email, dan kata sandi admin.',
    'Kata sandi minimal 6 karakter.': 'Kata sandi minimal 6 karakter.',
    'Kata Sandi (Password)': 'Kata Sandi (Password)',
    'Minimal 6 karakter.': 'Minimal 6 karakter.',
    'Pendaftaran & Rekap Akses Eksternal': 'Pendaftaran & Rekap Akses Eksternal',
    'Tinjau status verifikasi email, setujui/tolak permohonan akses katalog lelang oleh user umum.': 'Tinjau status verifikasi email, setujui/tolak permohonan akses katalog lelang oleh user umum.',
    'Cari nama, email, status...': 'Cari nama, email, status...',
    'Nama / No. HP': 'Nama / No. HP',
    'Alamat Email': 'Alamat Email',
    'Verifikasi Email': 'Verifikasi Email',
    'Status Akses': 'Status Akses',
    'Aksi Kelola': 'Aksi Kelola',
    'Verified': 'Verified',
    'Pending OTP': 'Pending OTP',
    'Akses Disetujui': 'Akses Disetujui',
    'Menunggu Approval': 'Menunggu Approval',
    'Menunggu Verifikasi': 'Menunggu Verifikasi',
    'Akses Ditolak': 'Akses Ditolak',
    'Setujui Pendaftaran': 'Setujui Pendaftaran',
    'Setujui': 'Setujui',
    'Tolak Pendaftaran': 'Tolak Pendaftaran',
    'Tolak': 'Tolak',
    'Ubah menjadi Setuju': 'Ubah menjadi Setuju',
    'Pulihkan & Setujui': 'Pulihkan & Setujui',
    'Tangguhkan Akses': 'Tangguhkan Akses',
    'Blokir Akses': 'Blokir Akses',
    'Hapus?': 'Hapus?',
    'Hapus Akun User Secara Permanen': 'Hapus Akun User Secara Permanen',
    'Tidak ada hasil pencarian yang cocok.': 'Tidak ada hasil pencarian yang cocok.',
    'Belum ada user eksternal yang mendaftar.': 'Belum ada user eksternal yang mendaftar.',
    'Dashboard Pancaran Lelang': 'Dashboard PLATINUM',
    'Halo Admin, kelola aset lelang komersial, pantau penawaran harga, dan atur survei fisik dalam satu portal terpadu.': 'Halo Admin, kelola aset lelang komersial, pantau penawaran harga, dan atur survei fisik dalam satu portal terpadu.',
    'Waktu Sistem (WIB)': 'Waktu Sistem (WIB)',
    'Sukses Lelang': 'Sukses Lelang',
    'Aset Aktif': 'Aset Aktif',
    'Partisipan Unik': 'Partisipan Unik',
    'Total Aset per Brand': 'Total Aset per Brand',
    'Porsi distribusi armada lelang Pancaran Logistics berdasarkan merek manufaktur.': 'Porsi distribusi armada lelang Pancaran Logistics berdasarkan merek manufaktur.',
    'Unit': 'Unit',
    'Belum ada data armada/brand tersedia.': 'Belum ada data armada/brand tersedia.',
    'Per 2026. Semua aset fisik di pool internal.': 'Per 2026. Semua aset fisik di pool internal.',
    'Jadwal Survei Fisik': 'Jadwal Survei Fisik',
    'Daftar booking kunjungan calon pembeli untuk inspeksi fisik kendaraan.': 'Daftar booking kunjungan calon pembeli untuk inspeksi fisik kendaraan.',
    'Semua': 'Semua',
    'Mendatang': 'Mendatang',
    'Riwayat': 'Riwayat',
    'Cari nama bidder, brand, atau armada...': 'Cari nama bidder, brand, atau armada...',
    'Selesai': 'Selesai',
    'Bidder': 'Bidder',
    'Lihat Aset': 'Lihat Aset',
    'Tidak ada jadwal survei fisik ditemukan.': 'Tidak ada jadwal survei fisik ditemukan.',
    'Portal Penawaran Umum (External)': 'Portal Penawaran Umum (Eksternal)',
    'Truck & Heavy Equipment': 'Truck & Heavy Equipment',
    '( Pancaran Lelang Angkutan Truk, Industri, & Niaga Utama Modern )': '( Pancaran Lelang Angkutan Truk, Industri, & Niaga Utama Modern )',
    'Dapatkan truk tangki, wingbox, trailer, cargo van, dan alat berat kualitas terbaik langsung dari ekosistem operasional Pancaran Logistics. Transparan, terpercaya, dan aman dengan jadwal survei fisik mandiri.': 'Dapatkan truk tangki, wingbox, trailer, cargo van, dan alat berat kualitas terbaik langsung dari ekosistem operasional Pancaran Logistics. Transparan, terpercaya, dan aman dengan jadwal survei fisik mandiri.',
    'KIR & STNK Lengkap': 'KIR & STNK Lengkap',
    'Bebas Atur Waktu Inspeksi': 'Bebas Atur Waktu Inspeksi',
    'Bagaimana Cara Kerja?': 'Bagaimana Cara Kerja?',
    'Pilih armada aktif di bawah, ajukan penawaran harga Anda, dan pilih waktu survei fisik untuk memeriksa kondisi mesin langsung di Pool kami sebelum lelang ditutup.': 'Pilih armada aktif di bawah, ajukan penawaran harga Anda, dan pilih waktu survei fisik untuk memeriksa kondisi mesin langsung di Pool kami sebelum lelang ditutup.',
    'Katalog Armada Tersedia': 'Katalog Armada Tersedia',
    'Semua armada di bawah siap dilepas dengan penawaran harga terbaik.': 'Semua armada di bawah siap dilepas dengan penawaran harga terbaik.',
    'Cari armada...': 'Cari armada...',
    'Tidak ada armada lelang yang terdaftar atau sesuai filter.': 'Tidak ada armada lelang yang terdaftar atau sesuai filter.',
    'Lihat Semua Koleksi': 'Lihat Semua Koleksi',
    'AJUKAN TAWAran': 'AJUKAN TAWAran',
    'Tutup Panel': 'Tutup Panel',
    'Harga Awal:': 'Harga Awal:',
    'Bid Tertinggi:': 'Bid Tertinggi:',
    'Spesifikasi & Deskripsi Aset': 'Spesifikasi & Deskripsi Aset',
    'Nama Lengkap Anda *': 'Nama Lengkap Anda *',
    'Contoh: PT Samudera Transport': 'Contoh: PT Samudera Transport',
    'Alamat Email Kontak *': 'Alamat Email Kontak *',
    'No. Handphone / WhatsApp *': 'No. Handphone / WhatsApp *',
    'Contoh: 0812XXXXXXXX': 'Contoh: 0812XXXXXXXX',
    'Harga Bid Anda (IDR) *': 'Harga Bid Anda (IDR) *',
    'Minimal harga bid:': 'Minimal harga bid:',
    'Gunakan': 'Gunakan',
    'Booking Jadwal Survei Fisik': 'Booking Jadwal Survei Fisik',
    'Ingin cek kondisi mesin langsung di Pool?': 'Ingin cek kondisi mesin langsung di Pool?',
    'Tentukan Waktu Kunjungan Pool': 'Tentukan Waktu Kunjungan Pool',
    'Pilih Tanggal': 'Pilih Tanggal',
    'Pilih Sesi Jam': 'Pilih Sesi Jam',
    'Pagi Sesi 1 (09:00 WIB)': 'Pagi Sesi 1 (09:00 WIB)',
    'Pagi Sesi 2 (11:00 WIB)': 'Pagi Sesi 2 (11:00 WIB)',
    'Siang Sesi 1 (13:30 WIB)': 'Siang Sesi 1 (13:30 WIB)',
    'Sore Sesi 2 (15:30 WIB)': 'Sore Sesi 2 (15:30 WIB)',
    'Lokasi inspeksi:': 'Lokasi inspeksi:',
    'Tim teknis Pancaran Group akan mendampingi Anda di lokasi.': 'Tim teknis Pancaran Group akan mendampingi Anda di lokasi.',
    'Kirim Penawaran & Booking': 'Kirim Penawaran & Booking',
    'Kirim Penawaran': 'Kirim Penawaran',
    'Penawaran Berhasil Dikirim!': 'Penawaran Berhasil Dikirim!',
    'Harga penawaran Anda telah dicatat ke dalam sistem Pancaran.': 'Harga penawaran Anda telah dicatat ke dalam sistem Pancaran.',
    'Armada:': 'Armada:',
    'Harga Bid Anda:': 'Harga Bid Anda:',
    'Jadwal Survei Fisik:': 'Jadwal Survei Fisik:',
    'Halaman ini akan kembali ke katalog dalam beberapa detik...': 'Halaman ini akan kembali ke katalog dalam beberapa detik...',
    'Dengan mengirimkan penawaran, Anda menyatakan tunduk pada Syarat & Ketentuan Umum Lelang Pancaran Logistics. Penawaran bersifat mengikat.': 'Dengan mengirimkan penawaran, Anda menyatakan tunduk pada Syarat & Ketentuan Umum Lelang Pancaran Logistics. Penawaran bersifat mengikat.',
    'FORM PENAWARAN': 'FORM PENAWARAN',
    'Ajukan Tawaran & Survei': 'Ajukan Tawaran & Survei',
    'Booking / Kirim Penawaran': 'Booking / Kirim Penawaran',
    'Penawaran Berhasil!': 'Penawaran Berhasil!',
    'Harga penawaran Anda telah dicatat.': 'Harga penawaran Anda telah dicatat.',
    'Harga Bid:': 'Harga Bid:',
    'Survei:': 'Survei:',
    'Menutup halaman...': 'Menutup halaman...',
    'Tulis Penawaran': 'Tulis Penawaran',
    'Deskripsi Lengkap': 'Deskripsi Lengkap',
    'Selengkapnya': 'Selengkapnya',
    'Detail Deskripsi': 'Detail Deskripsi',
    'Armada Baru Terdaftar': 'Armada Baru Terdaftar',
    'telah terdaftar di katalog.': 'telah terdaftar di katalog.',
    'Penawaran Baru Masuk': 'Penawaran Baru Masuk',
    'menawar': 'menawar',
    'untuk': 'untuk',
    'Status Unit Diperbarui': 'Status Unit Diperbarui',
    'sekarang berstatus': 'sekarang berstatus',
    'Buka / Aktif': 'Buka / Aktif',
    'Sold / Terjual': 'Sold / Terjual',
    'Spesifikasi Diperbarui': 'Spesifikasi Diperbarui',
    'Informasi unit': 'Informasi unit',
    'telah diperbarui.': 'telah diperbarui.',
    'Unit Dihapus': 'Unit Dihapus',
    'telah dihapus dari sistem.': 'telah dihapus dari sistem.',
    'Admin Baru Terdaftar': 'Admin Baru Terdaftar',
    'sekarang memiliki hak akses.': 'sekarang memiliki hak akses.',
    'Akses Admin Dicabut': 'Akses Admin Dicabut',
    'Akses untuk': 'Akses untuk',
    'telah dihapus.': 'telah dihapus.',
    'Notifikasi Terkini': 'Notifikasi Terkini',
    'Tidak ada notifikasi baru': 'Tidak ada notifikasi baru',
    'Jadwal Survei Diperbarui': 'Jadwal Survei Diperbarui',
    'Jadwal kunjungan': 'Jadwal kunjungan',
    'diperbarui menjadi': 'diperbarui menjadi',
    'Jadwal Survei Dibatalkan': 'Jadwal Survei Dibatalkan',
    'telah dibatalkan.': 'telah dibatalkan.',
    'Ubah Jadwal': 'Ubah Jadwal',
    'Simpan Jadwal': 'Simpan Jadwal',
    'Pilih Tanggal Baru': 'Pilih Tanggal Baru',
    'Pilih Sesi Baru': 'Pilih Sesi Baru',
    'Semua Notifikasi': 'Semua Notifikasi',
    'Bersihkan': 'Bersihkan',
    'booking jadwal survei': 'booking jadwal survei',
    'Atur Jadwal Kunjungan': 'Atur Jadwal Kunjungan',
    'Belum ada jadwal survei.': 'Belum ada jadwal survei.',
    'Atur Jadwal Baru': 'Atur Jadwal Baru',
    'Tanggal': 'Tanggal',
    'Sesi Jam': 'Sesi Jam',
    'Simpan': 'Simpan',
    'Daftar Booking': 'Daftar Booking',
    'Log Notifikasi': 'Log Notifikasi',
    'Lihat Unit': 'Lihat Unit',
    'Belum ada jadwal booking survei.': 'Belum ada jadwal booking survei.',
    'Batalkan Booking': 'Batalkan Booking',
    'Apakah Anda yakin ingin membatalkan jadwal booking survei ini?': 'Apakah Anda yakin ingin membatalkan jadwal booking survei ini?',
    'Hapus Penawaran': 'Hapus Penawaran',
    'Apakah Anda yakin ingin menghapus penawaran ini?': 'Apakah Anda yakin ingin menghapus penawaran ini?',
    'Apakah Anda yakin ingin membatalkan jadwal survei ini?': 'Apakah Anda yakin ingin membatalkan jadwal survei ini?',
    'INFORMASI UTAMA (MAIN INFORMATION)': 'INFORMASI UTAMA (MAIN INFORMATION)',
    'DETAIL SPESIFIKASI KENDARAAN (VEHICLE SPECIFICATION DETAILS)': 'DETAIL SPESIFIKASI KENDARAAN (VEHICLE SPECIFICATION DETAILS)',
    'DOKUMEN & LEGALITAS KENDARAAN (VEHICLE DOCUMENTS & LEGALITY)': 'DOKUMEN & LEGALITAS KENDARAAN (VEHICLE DOCUMENTS & LEGALITY)',
    'SPESIFIKASI ATTACHMENT (ATTACHMENT SPECIFICATIONS)': 'SPESIFIKASI ATTACHMENT (ATTACHMENT SPECIFICATIONS)',
    'KEUR BERLAKU HINGGA': 'KEUR BERLAKU HINGGA',
    'PLAT STNK BERLAKU HINGGA': 'PLAT STNK BERLAKU HINGGA',
    'PAJAK STNK BERLAKU HINGGA': 'PAJAK STNK BERLAKU HINGGA',
    'Pilih Foto Attachment': 'Pilih Foto Attachment',
    'Contoh: FMX, Ranger, Giga': 'Contoh: FMX, Ranger, Giga',
    'Contoh: 12.0 x 2.5 x 3.7 m': 'Contoh: 12.0 x 2.5 x 3.7 m',
    'Contoh: B 9912 PXT (kosongkan jika alat berat)': 'Contoh: B 9912 PXT (kosongkan jika alat berat)',
    'Contoh: 150.000.000': 'Contoh: 150.000.000',
    'Contoh: Pool Marunda Blok C, Jakut': 'Contoh: Pool Marunda Blok C, Jakut',
    'Contoh: 2.2 atau 3.0': 'Contoh: 2.2 atau 3.0',
    'Contoh: 2016': 'Contoh: 2016',
    'Contoh: JKTI915545': 'Contoh: JKTI915545',
    'Contoh: 40 M atau 12.0': 'Contoh: 40 M atau 12.0',
    'Contoh: 60 Ton': 'Contoh: 60 Ton',
    'Contoh: 1.5 M': 'Contoh: 1.5 M',
    'Contoh: - atau 1.5 M': 'Contoh: - atau 1.5 M',
    'Contoh: Fuso Ranger FL Wingbox 2022': 'Contoh: Fuso Ranger FL Wingbox 2022',
    'Contoh: 6x4, 4x2': 'Contoh: 6x4, 4x2',
    'Contoh: Mitsubishi, Volvo': 'Contoh: Mitsubishi, Volvo',
    'Contoh: Trailer, Tronton, Box': 'Contoh: Trailer, Tronton, Box',
    'Contoh: Rusak Ringan, Rekondisi': 'Contoh: Rusak Ringan, Rekondisi',
    'Contoh: 280 HP atau 340': 'Contoh: 280 HP atau 340',
    'Contoh: 150.000 atau 75.000': 'Contoh: 150.000 atau 75.000',
    'Jelaskan kondisi mesin, transmisi, kelengkapan surat KIR/STNK, riwayat perawatan, dsb.': 'Jelaskan kondisi mesin, transmisi, kelengkapan surat KIR/STNK, riwayat perawatan, dsb.',
    'Kelola Master Merek': 'Kelola Master Merek',
    'Kelola Master Kategori': 'Kelola Master Kategori',
    'Kelola Master Kondisi': 'Kelola Master Kondisi',
    'Kelola Master Seri': 'Kelola Master Seri',
    'Kelola Master Warna': 'Kelola Master Warna',
    'Kelola Master Bahan Bakar': 'Kelola Master Bahan Bakar',
    'Kelola Master Jenis Gandengan': 'Kelola Master Jenis Gandengan',
    'Kelola Master Tipe Gandengan': 'Kelola Master Tipe Gandengan',
    'Tidak ada Syarat & Ketentuan khusus (Kosong)': 'Tidak ada Syarat & Ketentuan khusus (Kosong)',
    'Syarat & Ketentuan Lelang (TNC)': 'Syarat & Ketentuan Lelang (TNC)',
    'Opsional. Masukkan syarat & ketentuan lelang khusus untuk unit ini. Jika dikosongkan, area Syarat & Ketentuan tidak akan menampilkan ketentuan apapun.': 'Opsional. Masukkan syarat & ketentuan lelang khusus untuk unit ini. Jika dikosongkan, area Syarat & Ketentuan tidak akan menampilkan ketentuan apapun.',
    'Mohon lengkapi data harga awal, lokasi, dan kategori.': 'Mohon lengkapi data harga awal, lokasi, dan kategori.',
    'Pilih Kategori': 'Pilih Kategori',
    'Daftar Seluruh Aset': 'Daftar Seluruh Aset',
    'Daftar Aset Terjual': 'Daftar Aset Terjual',
    'Daftar Aset Aktif': 'Daftar Aset Aktif',
    'Daftar Bidder / Peserta Lelang': 'Daftar Bidder / Peserta Lelang',
    'Daftar Akses Internal (Admin)': 'Daftar Akses Internal (Admin)',
    'Daftar Akses Eksternal (Pengguna)': 'Daftar Akses Eksternal (Pengguna)',
    'Menampilkan': 'Menampilkan',
    'data hasil filter': 'data hasil filter',
    'Cari data...': 'Cari data...',
    'Reset': 'Reset',
    'Harga Akhir': 'Harga Akhir',
    'Menawar Unit': 'Menawar Unit',
    'Terdaftar': 'Terdaftar',
    'Tidak ada data yang cocok dengan pencarian.': 'Tidak ada data yang cocok dengan pencarian.',
    'Dokumen & Legalitas': 'Dokumen & Legalitas',
    'KEUR Berlaku Hingga': 'KEUR Berlaku Hingga',
    'Plat STNK Berlaku Hingga': 'Plat STNK Berlaku Hingga',
    'Pajak STNK Berlaku Hingga': 'Pajak STNK Berlaku Hingga',
    'Spesifikasi Attachment': 'Spesifikasi Attachment',
    'Tahun Produksi': 'Tahun Produksi',
    'Dimensi Attachment': 'Dimensi Attachment',
    'Panjang Total': 'Panjang Total',
    'Lebar Total': 'Lebar Total',
    'Tinggi Total': 'Tinggi Total',
    'Syarat & Ketentuan Lelang *': 'Syarat & Ketentuan Lelang *',
    'Saya telah membaca, memahami, dan menyetujui seluruh Syarat dan Ketentuan Lelang yang berlaku.': 'Saya telah membaca, memahami, dan menyetujui seluruh Syarat dan Ketentuan Lelang yang berlaku.',
    'Setiap pengiriman penawaran dijamin aman & tunduk pada Syarat Ketentuan Lelang Pancaran.': 'Setiap pengiriman penawaran dijamin aman & tunduk pada Syarat Ketentuan Lelang Pancaran.',
    'No. Polisi': 'No. Polisi',
    'Ikhtisar Spesifikasi': 'Ikhtisar Spesifikasi',
    'Spesifikasi Utama': 'Spesifikasi Utama',
    'Tahun Registrasi': 'Tahun Registrasi',
    'No Polisi': 'No Polisi',
    'Lokasi Detail': 'Lokasi Detail',
    'Warna': 'Warna',
    'Detail Harga': 'Detail Harga',
    'Harga dikunci': 'Harga dikunci',
    'Silakan masuk atau daftar akun baru untuk melihat harga lelang dan melakukan penawaran.': 'Silakan masuk atau daftar akun baru untuk melihat harga lelang dan melakukan penawaran.',
    'Formulir Penawaran Terkunci': 'Formulir Penawaran Terkunci',
    'Silakan masuk atau daftar menggunakan akun lelang terverifikasi Anda untuk mengajukan penawaran lelang.': 'Silakan masuk atau daftar menggunakan akun lelang terverifikasi Anda untuk mengajukan penawaran lelang.',
    'Kembali': 'Kembali',
    'Tidak ada foto': 'Tidak ada foto',
    'Lihat Gambar Full': 'Lihat Gambar Full',
    'UNIT PILIHAN': 'UNIT PILIHAN',
    'BOOKING AMAN': 'BOOKING AMAN',
    'VERIFIED SELLER': 'VERIFIED SELLER',
    'Katalog': 'Katalog',
    'Notifikasi': 'Notifikasi',
    'Inbox': 'Inbox',
    'Penawaran Berhasil Diajukan': 'Penawaran Berhasil Diajukan',
    'Penawaran Anda sebesar {price} berhasil diajukan untuk {unit}.': 'Penawaran Anda sebesar {price} berhasil diajukan untuk {unit}.',
    '⚠️ Penawaran Terlampaui!': '⚠️ Penawaran Terlampaui!',
    'Penawar lain telah mengajukan harga lebih tinggi yaitu {price} pada {unit}. Silakan tawar kembali untuk memenangkan lelang.': 'Penawar lain telah mengajukan harga lebih tinggi yaitu {price} pada {unit}. Silakan tawar kembali untuk memenangkan lelang.',
    '🏆 Selamat, Anda Pemenang!': '🏆 Selamat, Anda Pemenang!',
    'Lelang ditutup. Anda memenangkan penawaran untuk {unit} dengan harga {price}. Surat resmi pemenang dikirim ke Inbox Anda.': 'Lelang ditutup. Anda memenangkan penawaran untuk {unit} dengan harga {price}. Surat resmi pemenang dikirim ke Inbox Anda.',
    'Lelang Ditutup (Terjual)': 'Lelang Ditutup (Terjual)',
    'Unit {unit} telah terjual kepada penawar tertinggi lain. Terima kasih atas partisipasi Anda.': 'Unit {unit} telah terjual kepada penawar tertinggi lain. Terima kasih atas partisipasi Anda.',
    'Notifikasi Saya': 'Notifikasi Saya',
    'Pantau riwayat penawaran, status outbid, dan pengumuman lelang Anda secara real-time.': 'Pantau riwayat penawaran, status outbid, dan pengumuman lelang Anda secara real-time.',
    'Belum ada notifikasi aktivitas lelang Anda.': 'Belum ada notifikasi aktivitas lelang Anda.',
    'Silakan lakukan penawaran pada katalog unit untuk memulai.': 'Silakan lakukan penawaran pada katalog unit untuk memulai.',
    'Surat resmi penunjukan pemenang lelang dikirim secara eksklusif ke email pemenang di sini.': 'Surat resmi penunjukan pemenang lelang dikirim secara eksklusif ke email pemenang di sini.',
    'Hanya pemenang lelang tertinggi yang akan menerima surat pengumuman pemenang di kotak masuk.': 'Hanya pemenang lelang tertinggi yang akan menerima surat pengumuman pemenang di kotak masuk.',
    'Tanggal & Waktu Penutupan Bid (Close Bid Date & Time)': 'Tanggal & Waktu Penutupan Bid (Close Bid Date & Time)',
    'Kosongkan jika lelang tidak memiliki batas waktu penutupan otomatis.': 'Kosongkan jika lelang tidak memiliki batas waktu penutupan otomatis.',
    'Tanggal Penutupan Bid': 'Tanggal Penutupan Bid',
    'Maaf, lelang untuk unit ini sudah ditutup karena telah melewati batas waktu penutupan.': 'Maaf, lelang untuk unit ini sudah ditutup karena telah melewati batas waktu penutupan.',
    'Lelang Ditutup': 'Lelang Ditutup',
    'Lelang untuk unit ini telah resmi ditutup pada': 'Lelang untuk unit ini telah resmi ditutup pada',
    'Batas Waktu Bidding': 'Batas Waktu Bidding',
    'Lelang ini akan ditutup secara otomatis pada': 'Lelang ini akan ditutup secara otomatis pada',
    'Penawaran untuk unit ini telah ditutup karena melewati batas waktu penutupan lelang.': 'Penawaran untuk unit ini telah ditutup karena melewati batas waktu penutupan lelang.',
    'Sisa Waktu': 'Sisa Waktu',
    'Hari': 'Hari',
    'Jam': 'Jam',
    'Menit': 'Menit',
    'Detik': 'Detik',
    'Close Bid': 'Close Bid',
    'Lupa Password?': 'Lupa Password?',
    'Reset Password': 'Reset Password',
    'Kembali ke Menu Masuk': 'Kembali ke Menu Masuk',
    'Masukkan Email Anda': 'Masukkan Email Anda',
    'Email tidak terdaftar atau salah.': 'Email tidak terdaftar atau salah.',
    'OTP reset password telah dikirim ke email Anda.': 'OTP reset password telah dikirim ke email Anda.',
    'Masukkan Kode OTP & Password Baru': 'Masukkan Kode OTP & Password Baru',
    'Kode OTP': 'Kode OTP',
    'Password Baru': 'Password Baru',
    'Konfirmasi Password Baru': 'Konfirmasi Password Baru',
    'Password berhasil direset! Silakan login kembali.': 'Password berhasil direset! Silakan login kembali.',
    'Password minimal 6 karakter.': 'Password minimal 6 karakter.',
    'Password tidak cocok.': 'Password tidak cocok.',
    'Kode OTP salah atau tidak cocok.': 'Kode OTP salah atau tidak cocok.',
    'Kirim OTP': 'Kirim OTP',
    'Verifikasi & Reset': 'Verifikasi & Reset',
    'Reset Password Berhasil': 'Reset Password Berhasil',
  },
  en: {
    'Pancaran Lelang': 'PLATINUM',
    'Katalog Eksternal': 'External Catalog',
    'Katalog Eksternal (Public)': 'External Catalog (Public)',
    'Area Admin Internal': 'Internal Admin Area',
    'Login Admin': 'Admin Login',
    'Logout Admin': 'Admin Logout',
    'Admin Active': 'Admin Active',
    'Keluar': 'Logout',
    'Pilih Tampilan': 'Select View',
    'Menu Admin': 'Admin Menu',
    'Dashboard Ringkasan': 'Dashboard Summary',
    'Kelola Aset (Tambah & Bids)': 'Manage Assets (Add & Bids)',
    'Manajemen Akses': 'Access Management',
    'Setelan Sistem': 'System Settings',
    'Status Koneksi': 'Connection Status',
    'Google Spreadsheet': 'Google Spreadsheet',
    'Sinkronisasi otomatis aktif per detik. Klik tombol di bawah untuk paksa sinkronisasi sekarang.': 'Automatic sync is active every second. Click the button below to force synchronization now.',
    'Menyinkronkan...': 'Syncing...',
    'Sinkronisasi Manual': 'Manual Sync',
    'Sedang menyinkronkan...': 'Syncing in progress...',
    'Berhasil disinkronkan!': 'Successfully synchronized!',
    'Gagal sinkronisasi.': 'Sync failed.',
    'Spreadsheet Sync': 'Spreadsheet Sync',
    'Sync Spreadsheet': 'Sync Spreadsheet',
    'Sinkronisasi Google Spreadsheet berhasil diselesaikan.': 'Google Spreadsheet synchronization completed successfully.',
    'Gagal sinkronisasi dengan Google Spreadsheet.': 'Failed to synchronize with Google Spreadsheet.',
    'Lelang Aktif': 'Active Auctions',
    'Sedang Berjalan': 'In Progress',
    'Unit Terjual': 'Sold Units',
    'Otorisasi Diperlukan': 'Authorization Required',
    'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.': 'The internal management page of Pancaran Lelang is protected by encryption. Please log in using your account credentials.',
    'Masuk Sekarang': 'Log In Now',
    'Hak Cipta Dilindungi': 'All Rights Reserved',
    'Pool Marunda': 'Marunda Pool',
    'Pool Cakung': 'Cakung Pool',
    'Pool Teluk Gong': 'Teluk Gong Pool',
    'Cilincing': 'Cilincing',
    'Admin Digital Solution': 'Digital Solution Admin',
    'AKUN MASUK:': 'LOGGED IN ACCOUNT:',
    'COMPANY INFO': 'COMPANY INFO',
    'Our Office': 'Our Office',
    'Head Office 1 :': 'Head Office 1 :',
    'HUBUNGI KAMI': 'CONTACT US',
    'Lokasi Pool Inspeksi:': 'Inspection Pool Locations:',
    'Portal resmi likuidasi armada aktif dan alat berat dari ekosistem operasional Pancaran Group. Transparan, tepercaya, dan terintegrasi.': 'Official portal for active fleet and heavy equipment liquidation from the Pancaran Group operational ecosystem. Transparent, trusted, and integrated.',
    'Syarat & Ketentuan': 'Terms & Conditions',
    'Kebijakan Privasi': 'Privacy Policy',
    'Cari aset lelang...': 'Search auction assets...',
    'Merek': 'Make',
    'Kategori': 'Category',
    'Kondisi': 'Condition',
    'Lokasi': 'Location',
    'Semua Merek': 'All Brands',
    'Semua Kategori': 'All Categories',
    'Semua Kondisi': 'All Conditions',
    'Semua Lokasi': 'All Locations',
    'Menampilkan {count} aset yang memenuhi kriteria': 'Showing {count} assets matching criteria',
    'Terbuka': 'Open',
    'Terjual': 'Sold',
    'Th': 'Yr',
    'Plat': 'Plate',
    'Harga Awal': 'Starting Price',
    'Harga Pembuka': 'Starting Price',
    'Penawaran Tertinggi': 'Highest Bid',
    'Penawaran Tertinggi:': 'Highest Bid:',
    'Belum ada penawaran': 'No bids yet',
    'Penawaran': 'Bid(s)',
    'Penawaran Masuk': 'Bids Submitted',
    'Tawar Aset': 'Place Bid',
    'Brand:': 'Brand:',
    'Kategori:': 'Category:',
    'Tahun:': 'Year:',
    'No. Polisi:': 'License Plate:',
    'Kondisi:': 'Condition:',
    'Lokasi:': 'Location:',
    'Lihat Detail': 'View Details',
    'Lihat Detail & Ajukan Bid': 'View Details & Submit Bid',
    'Detail Unit Lelang': 'Auction Unit Details',
    'Kembali ke Katalog': 'Back to Catalog',
    'Spesifikasi Unit': 'Unit Specifications',
    'Tahun Pembuatan': 'Year of Manufacture',
    'Nomor Polisi': 'License Plate',
    'Kondisi Fisik': 'Physical Condition',
    'Deskripsi Tambahan': 'Additional Description',
    'Informasi & Tata Cara Lelang': 'Auction Information & Procedure',
    'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.': 'This asset is first-hand, has complete legal documents (STNK, BPKB, KIR) and is ready to be transferred after full payment.',
    'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.': 'Bidding is conducted openly. Each new bid must be higher than the current bid.',
    'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.': 'After placing a bid, our logistics team will contact you for document verification and scheduling unit inspections at the respective pool location.',
    'Riwayat Penawaran Saat Ini': 'Current Bid History',
    'Nama': 'Name',
    'Nilai Bid': 'Bid Value',
    'Waktu': 'Time',
    'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!': 'No bids received yet for this unit. Be the first bidder!',
    'Formulir Pengajuan Bid Resmi': 'Official Bid Submission Form',
    'Masukkan nama lengkap Anda...': 'Enter your full name...',
    'Contoh: 08123456789': 'Example: 08123456789',
    'Masukkan alamat email aktif...': 'Enter active email address...',
    'Rencana Tanggal Survey': 'Planned Survey Date',
    'Rencana Jam Survey': 'Planned Survey Time',
    'Harga Penawaran Anda (Rupiah)': 'Your Bid Price (Rupiah)',
    'Min. Penawaran Berikutnya:': 'Min. Next Bid:',
    'Kirim Penawaran & Jadwalkan Survey': 'Submit Bid & Schedule Survey',
    'Memproses...': 'Processing...',
    'Silakan isi semua data dengan benar.': 'Please fill all fields correctly.',
    'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!': 'Your bid must be higher than the current highest bid!',
    'Penawaran Anda Berhasil Dikirim!': 'Your Bid Successfully Submitted!',
    'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.': 'Thank you for submitting a bid. The Pancaran Logistics team will contact you shortly at the provided contact details.',
    'Tutup': 'Close',
    'Pemenang Lelang': 'Auction Winner',
    'Pemenang': 'Winner',
    'Penawaran Pemenang': 'Winning Bid',
    'Kontak Pemenang': 'Winner Contact',
    'Belum ada penawar': 'No bidders yet',
    'Perkecil': 'Zoom Out',
    'Perbesar / Fokus Detail': 'Zoom In / Focus Detail',
    'Seret/Scroll untuk melihat bagian gambar • Klik gambar untuk mengecilkan': 'Drag/Scroll to view parts of the image • Click image to zoom out',
    'Klik gambar atau tombol untuk memperbesar penuh & jelas': 'Click image or button to zoom in full & clear',
    'Sudah Dibooking': 'Already Booked',
    'Pilih Tanggal Kunjungan': 'Select Visit Date',
    'Pilih Sesi Jam Kunjungan': 'Select Visit Time Session',
    'Ready': 'Ready',
    'Selected': 'Selected',
    'Booked': 'Booked',
    'Sesi Pagi I': 'Morning Session I',
    'Sesi Pagi II': 'Morning Session II',
    'Sesi Siang I': 'Afternoon Session I',
    'Sesi Sore II': 'Evening Session II',
    'Informasi Lokasi & Pendampingan': 'Location & Assistance Information',
    'Jadwal survei pada tanggal dan jam tersebut sudah di-booking oleh calon pembeli lain. Mohon pilih waktu atau hari lain.': 'The survey schedule for that date and time has been booked by another prospective buyer. Please choose another time or day.',
    'Klik gambar untuk berikutnya • Klik di luar untuk kembali': 'Click image for next • Click outside to go back',
    'Klik gambar atau di luar untuk kembali': 'Click image or outside to go back',
    'Klik gambar untuk memperkecil • Geser untuk menjelajah detail': 'Click image to zoom out • Drag to pan details',
    'Klik gambar untuk memperbesar • Klik di luar untuk kembali': 'Click image to zoom in • Click outside to return',
    'Zoom In': 'Zoom In',
    'Zoom Out': 'Zoom Out',
    'Otoritas Internal Admin': 'Internal Admin Authority',
    'Gunakan email & password terdaftar untuk mengelola sistem lelang.': 'Use registered email & password to manage the auction system.',
    'Email atau password salah. Pastikan kredensial benar.': 'Incorrect email or password. Please ensure credentials are correct.',
    'ALAMAT EMAIL KERJA': 'WORK EMAIL ADDRESS',
    'KATA SANDI (PASSWORD)': 'PASSWORD',
    'Masuk Aplikasi': 'Enter Application',
    'Petunjuk Akun Penguji:': 'Tester Account Tips:',
    'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.': 'To test admin features, click the button below to instantly fill default credentials.',
    'Isi Kredensial Penguji': 'Fill Tester Credentials',
    'Dashboard Utama & Analitik': 'Main Dashboard & Analytics',
    'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.': 'Real-time summary of Pancaran Logistics auction system performance metrics.',
    'Total Asset': 'Total Assets',
    'Unit di Database': 'Units in Database',
    'Sedang Aktif': 'Currently Active',
    'Menerima Penawaran': 'Accepting Bids',
    'Aset Terjual': 'Assets Sold',
    'Sudah Diproses': 'Processed',
    'Total Bidder': 'Total Bidders',
    'Telah Berpartisipasi': 'Have Participated',
    'Aset Terpopuler': 'Most Popular Asset',
    'Dengan Penawaran Terbanyak': 'With Most Bids',
    'Daftar Aktivitas Bid Terbaru': 'Recent Bid Activity List',
    'Aktivitas Terbaru': 'Recent Activity',
    'Daftar pengajuan penawaran harga dari calon pembeli eksternal.': 'List of price bid submissions from external prospective buyers.',
    'Semua Riwayat': 'All History',
    'Aset': 'Asset',
    'Penawar': 'Bidder',
    'Jumlah Penawaran': 'Bid Amount',
    'Tanggal & Waktu': 'Date & Time',
    'Status': 'Status',
    'Tindakan': 'Actions',
    'Belum ada aktivitas penawaran yang terdaftar di sistem.': 'No bid activity registered in the system yet.',
    'Lihat Detail Aset': 'View Asset Details',
    'Daftar Manajemen Aset': 'Asset Management List',
    'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.': 'Manage auctioned logistics units, add new units, and monitor incoming bid history.',
    'Tambah Unit Baru': 'Add New Unit',
    'Daftarkan Aset Lelang Baru': 'Register New Auction Asset',
    'Lengkapi spesifikasi teknis dan detail dokumen kendaraan di bawah.': 'Complete technical specifications and vehicle document details below.',
    'Ubah Detail Unit': 'Edit Unit Details',
    'Perbarui spesifikasi teknis dan kelengkapan dokumen kendaraan lelang.': 'Update technical specifications and completeness of auction vehicle documents.',
    'Semua Aset': 'All Assets',
    'Aktif / Open': 'Active / Open',
    'Terjual / Sold': 'Sold / Closed',
    'Cari aset...': 'Search assets...',
    'Tipe': 'Type',
    'Aksi': 'Actions',
    'Belum ada aset lelang yang cocok dengan pencarian Anda.': 'No auction assets match your search.',
    'PILIH TEMPLATE KENDARAAN (OPSIONAL)': 'SELECT VEHICLE TEMPLATE (OPTIONAL)',
    'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.': 'Selecting a template will automatically populate Name, Brand, Category, and standard illustration.',
    'FORMULIR MANAJEMEN UNIT ASET': 'UNIT ASSET MANAGEMENT FORM',
    'Nama Kendaraan / Aset': 'Vehicle / Asset Name',
    'Merek / Brand': 'Brand',
    'Kategori Kendaraan': 'Vehicle Category',
    'Tahun': 'Year',
    'Nomor Registrasi (Plat)': 'Registration Number (Plate)',
    'Sangat Baik': 'Excellent',
    'Baik': 'Good',
    'Cukup': 'Fair',
    'Butuh Perbaikan': 'Needs Repair',
    'Lokasi Pool': 'Pool Location',
    'Harga Awal (IDR)': 'Starting Price (IDR)',
    'Deskripsi & Spesifikasi Tambahan': 'Description & Additional Specs',
    'Batal': 'Cancel',
    'Simpan Perubahan': 'Save Changes',
    'Tambah Unit ke Sistem': 'Add Unit to System',
    'Unggah Foto Unit': 'Upload Unit Photo',
    'Klik untuk unggah atau seret foto ke sini': 'Click to upload or drag photo here',
    'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.': 'Format JPG, PNG max 5MB. Image will be automatically compressed for optimal performance.',
    'Foto berhasil diunggah': 'Photo successfully uploaded',
    'Hapus Foto': 'Delete Photo',
    'Gambar Utama': 'Primary Image',
    'PILIH ALAT BANTU': 'CHOOSE UTILITIES',
    'Dapatkan Saran Deskripsi dengan AI': 'Get Description Suggestions with AI',
    'Saran Deskripsi': 'Description Suggestions',
    'Gunakan Saran AI': 'Use AI Suggestion',
    'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.': 'Please select a template or fill in the Brand & Category first so that the AI can analyze relevant descriptions.',
    'Detail Histori Penawaran': 'Bid History Details',
    'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.': 'Select an asset on the left to view detailed specifications and full bid history.',
    'Detail Spesifikasi': 'Specification Details',
    'Histori Bid': 'Bid History',
    'Ubah Atribut': 'Edit Attributes',
    'Ubah Status': 'Edit Status',
    'Buka Penawaran': 'Open Bidding',
    'Tutup / Selesaikan (Sold)': 'Close / Complete (Sold)',
    'Hapus Unit': 'Delete Unit',
    'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?': 'Are you sure you want to permanently delete this asset from the database system?',
    'Ya, Hapus': 'Yes, Delete',
    'Tidak': 'No',
    'Rencana Survey:': 'Planned Survey:',
    'Belum ada penawaran untuk unit ini.': 'No bids for this unit.',
    'Bids Masuk': 'Incoming Bids',
    'Hubungi': 'Contact',
    'PLAT NOMOR': 'LICENSE PLATE',
    'TAHUN PRODUKSI': 'YEAR OF MANUFACTURE',
    'KONDISI FISIK': 'PHYSICAL CONDITION',
    'LOKASI SEEDING': 'POOL LOCATION',
    'DESKRIPSI INTERNAL': 'INTERNAL DESCRIPTION',
    'Histori Penawaran': 'Bid History',
    'Bids Tertinggi Pertama': 'Highest Bids First',
    'Jadwal Survei': 'Survey Schedule',
    'Belum ada penawaran harga masuk untuk aset ini.': 'No bids have been submitted for this asset yet.',
    'Konfirmasi Hapus Unit': 'Confirm Asset Deletion',
    'Edit Unit Aset': 'Edit Asset Unit',
    'Hapus Unit Aset': 'Delete Asset Unit',
    'Tutup Detail': 'Close Details',
    'Status Lelang Saat Ini:': 'Current Auction Status:',
    'Menerima Bid': 'Accepting Bids',
    'Buka Bid': 'Open Bidding',
    'Set Terjual': 'Set as Sold',
    'Sebelumnya': 'Previous',
    'Berikutnya': 'Next',
    'Tambah': 'Add',
    'Ketik atau tempel tautan gambar, lalu tekan tombol "Tambah" atau Enter untuk memasukkan ke galeri unit lelang ini.': 'Type or paste an image link, then press the "Add" button or Enter to add it to the gallery.',
    'Simpan Unit Baru': 'Save New Unit',
    'Kelola Aset Lelang': 'Manage Auction Assets',
    'Daftarkan armada logistik baru, pantau status lelang, dan verifikasi riwayat penawaran.': 'Register new logistics fleets, monitor auction statuses, and verify bid history.',
    'Tambah Aset Baru': 'Add New Asset',
    'Cari berdasarkan nama aset, plat, kategori...': 'Search by asset name, plate, category...',
    'Semua Brand': 'All Brands',
    'Tidak ada aset lelang yang cocok dengan kriteria pencarian.': 'No auction assets match your search criteria.',
    'Reset Semua Filter': 'Reset All Filters',
    'Merek (Brand) *': 'Make (Brand) *',
    'Kategori Unit *': 'Unit Category *',
    'Dimensi Unit': 'Unit Dimensions',
    'Dimensi Unit (Opsional)': 'Unit Dimensions (Optional)',
    'Model': 'Model',
    'Series': 'Series',
    'Axels': 'Axles',
    'Warna Kendaraan': 'Vehicle Colour',
    'Bahan Bakar': 'Fuel',
    'Horsepower (HP)': 'Horsepower (HP)',
    'KM Spidometer': 'Odometer KM',
    'Memiliki Attachment?': 'Have Attachment?',
    'Attachment': 'Attachment',
    'Detail Attachment': 'Attachment Detail',
    'Unggah Attachment': 'Upload Attachment',
    'Nomor KEUR': 'KEUR No',
    'Berlaku Hingga': 'Valid Until',
    'Panjang Total (Meter)': 'Total Length (Meter)',
    'Lebar Total (TON)': 'Total Width (TON)',
    'Tinggi Total (Meter)': 'Total Heigth (Meter)',
    'Ekstensi': 'Extention',
    'Dimensi': 'Dimensions',
    'Tahun Produksi *': 'Production Year *',
    'No. Registrasi / Plat Nomor': 'Registration No. / Plate Number',
    'Kondisi Fisik Unit *': 'Physical Condition *',
    'Harga Awal Lelang (IDR) *': 'Starting Price (IDR) *',
    'Lokasi Pool / Depo Unit *': 'Pool / Depot Location *',
    'Foto / Gambar Unit * (Bisa Unggah Banyak)': 'Unit Photos * (Supports Multiple Uploads)',
    'Pilih atau Seret Foto-Foto Armada': 'Select or Drag Fleet Photos',
    'Mendukung format PNG, JPG, JPEG (Bisa pilih banyak sekaligus, Max 5MB per file)': 'Supports PNG, JPG, JPEG formats (Can select multiple at once, Max 5MB per file)',
    'Koleksi Foto Terunggah ({count})': 'Uploaded Photo Gallery ({count})',
    'Cover Utama': 'Main Cover',
    'Tambah Foto via Tautan Gambar (URL)': 'Add Photo via Image Link (URL)',
    'Apakah Anda yakin ingin menghapus {name} secara permanen? Data historis penawaran juga akan ikut terhapus.': 'Are you sure you want to permanently delete {name}? Historical bid data will also be deleted.',
    'Akses Internal': 'Internal Access',
    'Total Akses Internal': 'Total Internal Access',
    'Total Akses Eksternal': 'Total External Access',
    'Administrator Aktif': 'Active Administrators',
    'Pengguna Terdaftar': 'Registered Users',
    'Kelola Hak Akses Admin': 'Manage Admin Privileges',
    'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.': 'Add, remove, and manage internal users who can access the administration dashboard.',
    'Daftarkan Admin Baru': 'Register New Admin',
    'Nama Lengkap': 'Full Name',
    'Alamat Email Pancaran': 'Pancaran Email Address',
    'Peran / Hak Akses': 'Role / Access Rights',
    'Super Admin': 'Super Admin',
    'Akses Eksternal': 'External Access',
    'Admin Operasional': 'Operational Admin',
    'Admin Keuangan': 'Financial Admin',
    'Daftarkan': 'Register',
    'Akun Terdaftar': 'Registered Accounts',
    'Peran': 'Role',
    'Bergabung': 'Joined',
    'Anda': 'You',
    'Hapus Akses': 'Revoke Access',
    'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?': 'Are you sure you want to revoke access rights for this admin?',
    'Manajemen Akses Admin': 'Admin Access Management',
    'Buat akses administrator baru, tinjau tingkatan hak akses, dan kelola otoritas keamanan internal Pancaran Lelang.': 'Create new administrator access, review privilege levels, and manage internal security authority for Pancaran Lelang.',
    'Buat Akses Baru': 'Create New Access',
    'Daftarkan akun email karyawan baru untuk memberikan akses masuk ke dashboard internal.': 'Register a new employee email account to grant access to the internal dashboard.',
    'Nama Lengkap Admin': 'Admin Full Name',
    'Contoh: Achmad Subagja': 'Example: Achmad Subagja',
    'Harus berupa email institusi Pancaran.': 'Must be an official Pancaran email.',
    'Tingkatan Peran (Role)': 'Role / Privilege Level',
    'Admin Operasional (Input & Kelola Aset)': 'Operational Admin (Input & Manage Assets)',
    'Admin Keuangan (Otorisasi Unit Terjual)': 'Financial Admin (Authorize Sold Units)',
    'Super Admin (Akses Penuh)': 'Super Admin (Full Access)',
    'Akses Eksternal (Catalog Only)': 'External Access (Catalog Only)',
    'Buat Hak Akses': 'Grant Access Rights',
    'Daftar Administrator Terdaftar': 'Registered Administrator List',
    'Daftar staf internal Pancaran Logistics yang memegang otoritas sistem Lelang.': 'List of internal Pancaran Logistics staff holding auction system authority.',
    'Nama / Karyawan': 'Name / Employee',
    'Email Akun': 'Account Email',
    'Terdaftar Pada': 'Registered On',
    'Ya': 'Yes',
    'Mohon lengkapi nama dan email admin.': 'Please complete the admin name and email fields.',
    'Email admin tersebut sudah terdaftar.': 'That admin email is already registered.',
    'Format email tidak valid. Direkomendasikan menggunakan email institusi Pancaran.': 'Invalid email format. It is recommended to use official Pancaran emails.',
    'Akses admin berhasil dibuat untuk': 'Admin access successfully created for',
    'Anda sedang masuk dengan akun ini': 'You are currently logged in with this account',
    'Akun Super Admin Utama tidak bisa dihapus': 'The primary Super Admin account cannot be deleted',
    'Kelola otentikasi staf internal dan persetujuan registrasi akses lelang untuk pihak eksternal.': 'Manage internal staff authentication and approve/reject auction access registration for external parties.',
    'Akses Admin Internal': 'Internal Admin Access',
    'Akses User Eksternal': 'External User Access',
    'Mohon lengkapi nama, email, dan kata sandi admin.': 'Please complete the name, email, and password fields.',
    'Kata sandi minimal 6 karakter.': 'Password must be at least 6 characters long.',
    'Kata Sandi (Password)': 'Password',
    'Minimal 6 karakter.': 'Minimum 6 characters.',
    'Pendaftaran & Rekap Akses Eksternal': 'Registration & External Access Recap',
    'Tinjau status verifikasi email, setujui/tolak permohonan akses katalog lelang oleh user umum.': 'Review email verification status, approve/reject catalog access requests from public users.',
    'Cari nama, email, status...': 'Search name, email, status...',
    'Nama / No. HP': 'Name / Phone No.',
    'Alamat Email': 'Email Address',
    'Verifikasi Email': 'Email Verification',
    'Status Akses': 'Access Status',
    'Aksi Kelola': 'Manage Action',
    'Verified': 'Verified',
    'Pending OTP': 'Pending OTP',
    'Akses Disetujui': 'Access Approved',
    'Menunggu Approval': 'Pending Approval',
    'Menunggu Verifikasi': 'Pending Verification',
    'Akses Ditolak': 'Access Rejected',
    'Setujui Pendaftaran': 'Approve Registration',
    'Setujui': 'Approve',
    'Tolak Pendaftaran': 'Reject Registration',
    'Tolak': 'Reject',
    'Ubah menjadi Setuju': 'Change to Approved',
    'Pulihkan & Setujui': 'Restore & Approve',
    'Tangguhkan Akses': 'Suspend Access',
    'Blokir Akses': 'Block Access',
    'Hapus?': 'Delete?',
    'Hapus Akun User Secara Permanen': 'Permanently Delete User Account',
    'Tidak ada hasil pencarian yang cocok.': 'No matching search results found.',
    'Belum ada user eksternal yang mendaftar.': 'No external users registered yet.',
    'Dashboard Pancaran Lelang': 'PLATINUM Dashboard',
    'Halo Admin, kelola aset lelang komersial, pantau penawaran harga, dan atur survei fisik dalam satu portal terpadu.': 'Hello Admin, manage commercial auction assets, monitor price bids, and organize physical surveys in one integrated portal.',
    'Waktu Sistem (WIB)': 'System Time (WIB)',
    'Sukses Lelang': 'Auction Success',
    'Aset Aktif': 'Active Assets',
    'Partisipan Unik': 'Unique Participants',
    'Total Aset per Brand': 'Total Assets per Brand',
    'Porsi distribusi armada lelang Pancaran Logistics berdasarkan merek manufaktur.': 'Distribution share of Pancaran Logistics\' auction fleet based on manufacturing brands.',
    'Unit': 'Units',
    'Belum ada data armada/brand tersedia.': 'No fleet/brand data available yet.',
    'Per 2026. Semua aset fisik di pool internal.': 'As of 2026. All physical assets located in internal pools.',
    'Jadwal Survei Fisik': 'Physical Survey Schedule',
    'Daftar booking kunjungan calon pembeli untuk inspeksi fisik kendaraan.': 'Booking list of prospective buyers visiting for physical vehicle inspection.',
    'Semua': 'All',
    'Mendatang': 'Upcoming',
    'Riwayat': 'History',
    'Cari nama bidder, brand, atau armada...': 'Search bidder name, brand, or fleet...',
    'Selesai': 'Finished',
    'Bidder': 'Bidder',
    'Lihat Aset': 'View Asset',
    'Tidak ada jadwal survei fisik ditemukan.': 'No physical survey schedule found.',
    'Portal Penawaran Umum (External)': 'Public Bidding Portal (External)',
    'Truck & Heavy Equipment': 'Truck & Heavy Equipment',
    '( Pancaran Lelang Angkutan Truk, Industri, & Niaga Utama Modern )': '( Pancaran Auction for Trucks, Industrial & Main Modern Commerce )',
    'Dapatkan truk tangki, wingbox, trailer, cargo van, dan alat berat kualitas terbaik langsung dari ekosistem operasional Pancaran Logistics. Transparan, terpercaya, dan aman dengan jadwal survei fisik mandiri.': 'Get the best quality tank trucks, wingboxes, trailers, cargo vans, and heavy equipment directly from the operational ecosystem of Pancaran Logistics. Transparent, reliable, and secure with self-scheduled physical surveys.',
    'KIR & STNK Lengkap': 'Complete KIR & STNK Registration',
    'Bebas Atur Waktu Inspeksi': 'Flexible Inspection Scheduling',
    'Bagaimana Cara Kerja?': 'How It Works',
    'Pilih armada aktif di bawah, ajukan penawaran harga Anda, dan pilih waktu survei fisik untuk memeriksa kondisi mesin langsung di Pool kami sebelum lelang ditutup.': 'Select an active fleet below, submit your price bid, and select a physical survey time to inspect the engine directly at our pool before the bidding closes.',
    'Katalog Armada Tersedia': 'Available Fleet Catalog',
    'Semua armada di bawah siap dilepas dengan penawaran harga terbaik.': 'All fleets below are ready to be released with the best price bids.',
    'Cari armada...': 'Search fleet...',
    'Tidak ada armada lelang yang terdaftar atau sesuai filter.': 'No auction fleets registered or matching the filter.',
    'Lihat Semua Koleksi': 'View All Collections',
    'AJUKAN TAWAran': 'SUBMIT OFFER',
    'Tutup Panel': 'Close Panel',
    'Harga Awal:': 'Starting Price:',
    'Bid Tertinggi:': 'Highest Bid:',
    'Spesifikasi & Deskripsi Aset': 'Asset Specifications & Description',
    'Nama Lengkap Anda *': 'Your Full Name *',
    'Contoh: PT Samudera Transport': 'Example: PT Samudera Transport',
    'Alamat Email Kontak *': 'Contact Email Address *',
    'No. Handphone / WhatsApp *': 'Mobile Number / WhatsApp *',
    'Contoh: 0812XXXXXXXX': 'Example: 0812XXXXXXXX',
    'Harga Bid Anda (IDR) *': 'Your Bid Price (IDR) *',
    'Minimal harga bid:': 'Minimum bid price:',
    'Gunakan': 'Use',
    'Booking Jadwal Survei Fisik': 'Book Physical Survey Schedule',
    'Ingin cek kondisi mesin langsung di Pool?': 'Want to check engine condition directly at the Pool?',
    'Tentukan Waktu Kunjungan Pool': 'Set Pool Visit Time',
    'Pilih Tanggal': 'Select Date',
    'Pilih Sesi Jam': 'Select Time Session',
    'Pagi Sesi 1 (09:00 WIB)': 'Morning Session 1 (09:00 WIB)',
    'Pagi Sesi 2 (11:00 WIB)': 'Morning Session 2 (11:00 WIB)',
    'Siang Sesi 1 (13:30 WIB)': 'Afternoon Session 1 (13:30 WIB)',
    'Sore Sesi 2 (15:30 WIB)': 'Evening Session 2 (15:30 WIB)',
    'Lokasi inspeksi:': 'Inspection location:',
    'Tim teknis Pancaran Group akan mendampingi Anda di lokasi.': 'The Pancaran Group technical team will assist you on site.',
    'Kirim Penawaran & Booking': 'Submit Bid & Book',
    'Kirim Penawaran': 'Submit Bid',
    'Penawaran Berhasil Dikirim!': 'Bid Successfully Submitted!',
    'Harga penawaran Anda telah dicatat ke dalam sistem Pancaran.': 'Your bid price has been recorded into the Pancaran system.',
    'Armada:': 'Fleet:',
    'Harga Bid Anda:': 'Your Bid Price:',
    'Jadwal Survei Fisik:': 'Physical Survey Schedule:',
    'Halaman ini akan kembali ke katalog dalam beberapa detik...': 'This page will return to the catalog in a few seconds...',
    'Dengan mengirimkan penawaran, Anda menyatakan tunduk pada Syarat & Ketentuan Umum Lelang Pancaran Logistics. Penawaran bersifat mengikat.': 'By submitting an offer, you agree to the General Terms & Conditions of Pancaran Logistics Auctions. Bids are binding.',
    'FORM PENAWARAN': 'BID FORM',
    'Ajukan Tawaran & Survei': 'Submit Bid & Survey',
    'Booking / Kirim Penawaran': 'Book / Submit Bid',
    'Penawaran Berhasil!': 'Bid Successful!',
    'Harga penawaran Anda telah dicatat.': 'Your bid price has been recorded.',
    'Harga Bid:': 'Bid Price:',
    'Survei:': 'Survey:',
    'Menutup halaman...': 'Closing page...',
    'Tulis Penawaran': 'Submit Bid',
    'Deskripsi Lengkap': 'Full Description',
    'Selengkapnya': 'Show More',
    'Detail Deskripsi': 'Detailed Description',
    'Armada Baru Terdaftar': 'New Fleet Registered',
    'telah terdaftar di katalog.': 'has been registered in the catalog.',
    'Penawaran Baru Masuk': 'New Bid Received',
    'menawar': 'bid',
    'untuk': 'for',
    'Status Unit Diperbarui': 'Unit Status Updated',
    'sekarang berstatus': 'is now status',
    'Buka / Aktif': 'Open / Active',
    'Sold / Terjual': 'Sold',
    'Spesifikasi Diperbarui': 'Specifications Updated',
    'Informasi unit': 'Unit information',
    'telah diperbarui.': 'has been updated.',
    'Unit Dihapus': 'Unit Deleted',
    'telah dihapus dari sistem.': 'has been deleted from the system.',
    'Admin Baru Terdaftar': 'New Admin Registered',
    'sekarang memiliki hak akses.': 'now has access rights.',
    'Akses Admin Dicabut': 'Admin Access Revoked',
    'Akses untuk': 'Access for',
    'telah dihapus.': 'has been deleted.',
    'Notifikasi Terkini': 'Latest Notifications',
    'Tidak ada notifikasi baru': 'No new notifications',
    'Jadwal Survei Diperbarui': 'Survey Schedule Updated',
    'Jadwal kunjungan': 'Visit schedule of',
    'diperbarui menjadi': 'has been updated to',
    'Jadwal Survei Dibatalkan': 'Survey Schedule Cancelled',
    'telah dibatalkan.': 'has been cancelled.',
    'Ubah Jadwal': 'Reschedule',
    'Simpan Jadwal': 'Save Schedule',
    'Pilih Tanggal Baru': 'Select New Date',
    'Pilih Sesi Baru': 'Select New Session',
    'Semua Notifikasi': 'All Notifications',
    'Bersihkan': 'Clear All',
    'booking jadwal survei': 'booking survey schedule on',
    'Atur Jadwal Kunjungan': 'Set Visit Schedule',
    'Belum ada jadwal survei.': 'No survey schedule set.',
    'Atur Jadwal Baru': 'Set New Schedule',
    'Tanggal': 'Date',
    'Sesi Jam': 'Session',
    'Simpan': 'Save',
    'Daftar Booking': 'Booking List',
    'Log Notifikasi': 'Notification Logs',
    'Lihat Unit': 'View Unit',
    'Belum ada jadwal booking survei.': 'No survey bookings found.',
    'Batalkan Booking': 'Cancel Booking',
    'Apakah Anda yakin ingin membatalkan jadwal booking survei ini?': 'Are you sure you want to cancel this survey booking schedule?',
    'Hapus Penawaran': 'Delete Bid',
    'Apakah Anda yakin ingin menghapus penawaran ini?': 'Are you sure you want to delete this bid?',
    'Apakah Anda yakin ingin membatalkan jadwal survei ini?': 'Are you sure you want to cancel this survey schedule?',
    'Masuk ke Pancaran Lelang': 'Log in to Pancaran Lelang',
    'Gunakan akun Anda untuk melihat harga dan melakukan penawaran.': 'Use your account to view prices and place bids.',
    'Daftar Akun Baru': 'Register New Account',
    'Lengkapi data Anda untuk mendapatkan akses penawaran unit lelang.': 'Complete your details to get access to auction unit bids.',
    'ALAMAT EMAIL': 'EMAIL ADDRESS',
    'Belum memiliki akun lelang?': 'Do not have an auction account?',
    'Daftar Di Sini': 'Register Here',
    'NAMA LENGKAP': 'FULL NAME',
    'Contoh: Budi Santoso': 'Example: Budi Santoso',
    'NOMOR HP / WHATSAPP': 'MOBILE / WHATSAPP NUMBER',
    'KATA SANDI (MINIMAL 6 KARAKTER)': 'PASSWORD (MINIMUM 6 CHARACTERS)',
    'Daftarkan Akun': 'Register Account',
    'Kembali ke Menu Masuk': 'Back to Login Menu',
    'Pendaftaran akun Anda berhasil, namun saat ini sedang menunggu persetujuan (approval) oleh Administrator Pancaran Logistics.': 'Your account registration was successful, but is currently awaiting approval by the Pancaran Logistics Administrator.',
    'Pendaftaran Berhasil Terkirim!': 'Registration Successfully Sent!',
    'Sesuai dengan kebijakan Pancaran Logistics, pendaftaran Anda saat ini berstatus': 'In accordance with Pancaran Logistics policy, your registration status is currently',
    'Menunggu Persetujuan Admin': 'Awaiting Admin Approval',
    'Administrator internal akan meninjau data pendaftaran Anda sebelum menyetujui akses ke katalog lelang.': 'The internal administrator will review your registration data before approving access to the auction catalog.',
    'Masuk / Daftar': 'Log In / Register',
    'Masuk / Daftar Sekarang': 'Log In / Register Now',
    'Pendaftaran Anda ditolak oleh Administrator. Hubungi support untuk informasi lebih lanjut.': 'Your registration has been rejected by the Administrator. Please contact support for more information.',
    'Email tidak terdaftar. Hubungi Admin atau gunakan menu Daftar Baru.': 'Email is not registered. Please contact Admin or use the Register menu.',
    'Terjadi kesalahan saat masuk. Hubungi Admin.': 'An error occurred during login. Please contact Admin.',
    'Kata sandi minimal harus 6 karakter.': 'Password must be at least 6 characters.',
    'Email ini sudah terdaftar sebagai akun Administrator.': 'This email is already registered as an Administrator account.',
    'Email ini sudah terdaftar. Silakan masuk menggunakan akun Anda.': 'This email is already registered. Please log in using your account.',
    'Gagal melakukan pendaftaran. Silakan coba kembali.': 'Failed to register. Please try again.',
    'Verifikasi Email Anda': 'Verify Your Email',
    'Masukkan kode verifikasi OTP yang dikirimkan untuk mengaktifkan akun.': 'Enter the verification OTP code sent to activate your account.',
    'Pendaftaran Selesai': 'Registration Complete',
    'Status akun Anda sedang menunggu konfirmasi admin.': 'Your account status is currently awaiting admin confirmation.',
    'Petunjuk Akun Penguji (Admin):': 'Tester Account Guide (Admin):',
    'Untuk masuk sebagai internal administrator Pancaran Logistics, silakan klik tombol di bawah untuk mengisi kredensial secara instan.': 'To log in as an internal administrator of Pancaran Logistics, please click the button below to fill in credentials instantly.',
    'KODE VERIFIKASI OTP': 'OTP VERIFICATION CODE',
    'Verifikasi Sekarang': 'Verify Now',
    'OTP Telah Dikirim ke Email Asli:': 'OTP Sent to Real Email:',
    'Sistem keamanan Pancaran Lelang telah mengirimkan 6 digit kode OTP ke email asli Anda. Silakan periksa Kotak Masuk (Inbox) atau folder Spam/Promosi Anda.': 'Pancaran Lelang security system has sent a 6-digit OTP code to your real email. Please check your Inbox or Spam/Promotion folder.',
    'Kode verifikasi disembunyikan dari web ini untuk keamanan autentik.': 'The verification code is hidden from this website for authentic security.',
    'Layanan Email Belum Dikonfigurasi:': 'Email Service Not Configured:',
    'Sistem email verifikasi asli belum dikonfigurasi oleh Administrator. Kode OTP tidak dapat ditampilkan di layar web demi keamanan data.': 'The real verification email system has not been configured by the Administrator. The OTP code cannot be displayed on the screen for data security.',
    '💡 Admin: Harap buka Setelan Admin dan masukkan URL Google Apps Script Web App agar kode verifikasi dapat terkirim secara otomatis ke email asli pendaftar.': '💡 Admin: Please open Admin Settings and enter the Google Apps Script Web App URL so that the verification code can be sent automatically to the registrant\'s real email.',
    'Batalkan Pendaftaran': 'Cancel Registration',
    '💡 Petunjuk Pengujian:': '💡 Testing Instructions:',
    '1. Masuk ke dashboard menggunakan Akun Admin.': '1. Log in to the dashboard using an Admin Account.',
    '2. Masuk ke menu "Manajemen Akses" > tab "Akses User Eksternal".': '2. Go to "Access Management" > "External User Access" tab.',
    '3. Cari email pendaftaran Anda lalu klik tombol "Setujui Akses" (Centang Hijau).': '3. Search for your registration email and click "Approve Access" (Green Checkmark).',
    '4. Setelah itu, Anda dapat masuk kembali dengan akun Anda untuk melihat harga lelang.': '4. After that, you can log in again with your account to view the auction prices.',
    'Kembali ke Halaman Masuk': 'Back to Login Page',
    'Email ini tidak terdaftar sebagai Administrator. Gunakan tab Akses Eksternal atau hubungi Developer.': 'This email is not registered as an Administrator. Please use the External Access tab or contact Developer.',
    'Email ini terdaftar sebagai akun Administrator. Silakan masuk melalui tab Super Admin.': 'This email is registered as an Administrator account. Please log in through the Super Admin tab.',
    'Akses Eksternal (Katalog Saja)': 'External Access (Catalog Only)',
    'INFORMASI UTAMA (MAIN INFORMATION)': 'MAIN INFORMATION',
    'DETAIL SPESIFIKASI KENDARAAN (VEHICLE SPECIFICATION DETAILS)': 'VEHICLE SPECIFICATION DETAILS',
    'DOKUMEN & LEGALITAS KENDARAAN (VEHICLE DOCUMENTS & LEGALITY)': 'VEHICLE DOCUMENTS & LEGALITY',
    'SPESIFIKASI ATTACHMENT (ATTACHMENT SPECIFICATIONS)': 'ATTACHMENT SPECIFICATIONS',
    'KEUR BERLAKU HINGGA': 'KEUR VALID UNTIL',
    'PLAT STNK BERLAKU HINGGA': 'STNK PLATE VALID UNTIL',
    'PAJAK STNK BERLAKU HINGGA': 'STNK TAX VALID UNTIL',
    'Pilih Foto Attachment': 'Select Attachment Photo',
    'Contoh: FMX, Ranger, Giga': 'e.g., FMX, Ranger, Giga',
    'Contoh: 12.0 x 2.5 x 3.7 m': 'e.g., 12.0 x 2.5 x 3.7 m',
    'Contoh: B 9912 PXT (kosongkan jika alat berat)': 'e.g., B 9912 PXT (leave blank for heavy equipment)',
    'Contoh: 150.000.000': 'e.g., 150,000,000',
    'Contoh: Pool Marunda Blok C, Jakut': 'e.g., Marunda Pool Block C, North Jakarta',
    'Contoh: 2.2 atau 3.0': 'e.g., 2.2 or 3.0',
    'Contoh: 2016': 'e.g., 2016',
    'Contoh: JKTI915545': 'e.g., JKTI915545',
    'Contoh: 40 M atau 12.0': 'e.g., 40 M or 12.0',
    'Contoh: 60 Ton': 'e.g., 60 Tons',
    'Contoh: 1.5 M': 'e.g., 1.5 M',
    'Contoh: - atau 1.5 M': 'e.g., - or 1.5 M',
    'Contoh: Fuso Ranger FL Wingbox 2022': 'e.g., Fuso Ranger FL Wingbox 2022',
    'Contoh: 6x4, 4x2': 'e.g., 6x4, 4x2',
    'Contoh: Mitsubishi, Volvo': 'e.g., Mitsubishi, Volvo',
    'Contoh: Trailer, Tronton, Box': 'e.g., Trailer, Tronton, Box',
    'Contoh: Rusak Ringan, Rekondisi': 'e.g., Light Damage, Reconditioned',
    'Contoh: 280 HP atau 340': 'e.g., 280 HP or 340',
    'Contoh: 150.000 atau 75.000': 'e.g., 150,000 or 75,000',
    'Jelaskan kondisi mesin, transmisi, kelengkapan surat KIR/STNK, riwayat perawatan, dsb.': 'Explain engine condition, transmission, completeness of KIR/STNK documents, maintenance history, etc.',
    'Kelola Master Merek': 'Manage Brand Master',
    'Kelola Master Kategori': 'Manage Category Master',
    'Kelola Master Kondisi': 'Manage Condition Master',
    'Kelola Master Seri': 'Manage Series Master',
    'Kelola Master Warna': 'Manage Colour Master',
    'Kelola Master Bahan Bakar': 'Manage Fuel Master',
    'Kelola Master Jenis Gandengan': 'Manage Attachment Category Master',
    'Kelola Master Tipe Gandengan': 'Manage Attachment Type Master',
    'Putih': 'White',
    'Merah': 'Red',
    'Kuning': 'Yellow',
    'Abu-Abu': 'Grey',
    'Hijau': 'Green',
    'Biru': 'Blue',
    'Hitam': 'Black',
    'Silver': 'Silver',
    'Cokelat': 'Brown',
    'Solar': 'Diesel',
    'Bensin': 'Petrol',
    'Cukup Baik': 'Fairly Good',
    'Rusak Berat': 'Severely Damaged',
    'Tambah atau hapus daftar pilihan seri kendaraan.': 'Add or delete vehicle series options list.',
    'Tambah Seri Baru': 'Add New Series',
    'Contoh: 500, GIGA, FL 260': 'e.g., 500, GIGA, FL 260',
    'Daftar Seri Aktif': 'Active Series List',
    'Tidak ada data seri.': 'No series data.',
    'Hapus Seri': 'Delete Series',
    'Tambah atau hapus daftar pilihan warna kendaraan.': 'Add or delete vehicle colour options list.',
    'Tambah Warna Baru': 'Add New Colour',
    'Contoh: Merah, Putih, Kuning': 'e.g., Red, White, Yellow',
    'Daftar Warna Aktif': 'Active Colours List',
    'Tidak ada data warna.': 'No colour data.',
    'Hapus Warna': 'Delete Colour',
    'Tambah atau hapus daftar pilihan jenis bahan bakar.': 'Add or delete fuel type options list.',
    'Tambah Bahan Bakar Baru': 'Add New Fuel Type',
    'Contoh: Solar, Diesel, Bensin': 'e.g., Diesel, Petrol',
    'Daftar Bahan Bakar Aktif': 'Active Fuels List',
    'Tidak ada data bahan bakar.': 'No fuel data.',
    'Hapus Bahan Bakar': 'Delete Fuel',
    'Tambah atau hapus daftar pilihan jenis gandengan.': 'Add or delete attachment category options list.',
    'Tambah Jenis Gandengan Baru': 'Add New Attachment Category',
    'Contoh: Trailer, Box, Dump Body': 'e.g., Trailer, Box, Dump Body',
    'Daftar Jenis Gandengan Aktif': 'Active Attachment Categories List',
    'Tidak ada data jenis gandengan.': 'No attachment category data.',
    'Hapus Jenis Gandengan': 'Delete Attachment Category',
    'Tambah atau hapus daftar pilihan tipe/model gandengan.': 'Add or delete attachment type/model options list.',
    'Tambah Tipe Gandengan Baru': 'Add New Attachment Type',
    'Contoh: Highbed 40, Skeleton 20': 'e.g., Highbed 40, Skeleton 20',
    'Daftar Tipe Gandengan Aktif': 'Active Attachment Types List',
    'Tidak ada data tipe gandengan.': 'No attachment type data.',
    'Hapus Tipe Gandengan': 'Delete Attachment Type',
    'Tidak ada Syarat & Ketentuan khusus (Kosong)': 'No specific Terms & Conditions (Empty)',
    'Syarat & Ketentuan Lelang (TNC)': 'Auction Terms & Conditions (TNC)',
    'Opsional. Masukkan syarat & ketentuan lelang khusus untuk unit ini. Jika dikosongkan, area Syarat & Ketentuan tidak akan menampilkan ketentuan apapun.': 'Optional. Enter specific auction terms & conditions for this unit. If left empty, the Terms & Conditions section will not display any rules.',
    'Mohon lengkapi data harga awal, lokasi, dan kategori.': 'Please complete starting price, location, and category data.',
    'Pilih Kategori': 'Select Category',
    'Daftar Seluruh Aset': 'All Assets List',
    'Daftar Aset Terjual': 'Sold Assets List',
    'Daftar Aset Aktif': 'Active Assets List',
    'Daftar Bidder / Peserta Lelang': 'Bidders / Auction Participants List',
    'Daftar Akses Internal (Admin)': 'Internal Access List (Admin)',
    'Daftar Akses Eksternal (Pengguna)': 'External Access List (User)',
    'Menampilkan': 'Showing',
    'data hasil filter': 'filtered data',
    'Cari data...': 'Search data...',
    'Reset': 'Reset',
    'Harga Akhir': 'Final Price',
    'Menawar Unit': 'Bidding on Units',
    'Terdaftar': 'Registered',
    'Tidak ada data yang cocok dengan pencarian.': 'No data matches the search.',
    'Dokumen & Legalitas': 'Documents & Legality',
    'KEUR Berlaku Hingga': 'KEUR Valid Until',
    'Plat STNK Berlaku Hingga': 'STNK Plate Valid Until',
    'Pajak STNK Berlaku Hingga': 'STNK Tax Valid Until',
    'Spesifikasi Attachment': 'Attachment Specifications',
    'Tahun Produksi': 'Production Year',
    'Dimensi Attachment': 'Attachment Dimensions',
    'Panjang Total': 'Total Length',
    'Lebar Total': 'Total Width',
    'Tinggi Total': 'Total Height',
    'Syarat & Ketentuan Lelang *': 'Auction Terms & Conditions *',
    'Saya telah membaca, memahami, dan menyetujui seluruh Syarat dan Ketentuan Lelang yang berlaku.': 'I have read, understood, and agreed to all applicable Auction Terms & Conditions.',
    'Setiap pengiriman penawaran dijamin aman & tunduk pada Syarat Ketentuan Lelang Pancaran.': 'Every bid submission is guaranteed secure & subject to Pancaran Auction Terms & Conditions.',
    'No. Polisi': 'Plate Number',
    'Ikhtisar Spesifikasi': 'Specification Overview',
    'Spesifikasi Utama': 'Main Specifications',
    'Tahun Registrasi': 'Registration Year',
    'No Polisi': 'Plate Number',
    'Lokasi Detail': 'Detailed Location',
    'Warna': 'Color',
    'Detail Harga': 'Price Details',
    'Harga dikunci': 'Price locked',
    'Silakan masuk atau daftar akun baru untuk melihat harga lelang dan melakukan penawaran.': 'Please login or register a new account to see the auction price and place a bid.',
    'Formulir Penawaran Terkunci': 'Bid Form Locked',
    'Silakan masuk atau daftar menggunakan akun lelang terverifikasi Anda untuk mengajukan penawaran lelang.': 'Please login or register using your verified auction account to submit an auction bid.',
    'Kembali': 'Back',
    'Tidak ada foto': 'No photos',
    'Lihat Gambar Full': 'View Full Image',
    'UNIT PILIHAN': 'FEATURED UNIT',
    'BOOKING AMAN': 'SECURE BOOKING',
    'VERIFIED SELLER': 'VERIFIED SELLER',
    'Katalog': 'Catalog',
    'Notifikasi': 'Notifications',
    'Inbox': 'Inbox',
    'Penawaran Berhasil Diajukan': 'Bid Successfully Submitted',
    'Penawaran Anda sebesar {price} berhasil diajukan untuk {unit}.': 'Your bid of {price} has been successfully submitted for {unit}.',
    '⚠️ Penawaran Terlampaui!': '⚠️ Bid Outbid!',
    'Penawar lain telah mengajukan harga lebih tinggi yaitu {price} pada {unit}. Silakan tawar kembali untuk memenangkan lelang.': 'Another bidder has submitted a higher price of {price} on {unit}. Please place another bid to win the auction.',
    '🏆 Selamat, Anda Pemenang!': '🏆 Congratulations, You Won!',
    'Lelang ditutup. Anda memenangkan penawaran untuk {unit} dengan harga {price}. Surat resmi pemenang dikirim ke Inbox Anda.': 'The auction is closed. You won the bid for {unit} at {price}. The official winner letter has been sent to your Inbox.',
    'Lelang Ditutup (Terjual)': 'Auction Closed (Sold)',
    'Unit {unit} telah terjual kepada penawar tertinggi lain. Terima kasih atas partisipasi Anda.': 'Unit {unit} has been sold to another highest bidder. Thank you for your participation.',
    'Notifikasi Saya': 'My Notifications',
    'Pantau riwayat penawaran, status outbid, dan pengumuman lelang Anda secara real-time.': 'Monitor your bidding history, outbid status, and auction announcements in real-time.',
    'Belum ada notifikasi aktivitas lelang Anda.': 'There are no auction activity notifications yet.',
    'Silakan lakukan penawaran pada katalog unit untuk memulai.': 'Please place a bid on the unit catalog to start.',
    'Surat resmi penunjukan pemenang lelang dikirim secara eksklusif ke email pemenang di sini.': 'The official auction winner letter is sent exclusively to the winner\'s email here.',
    'Hanya pemenang lelang tertinggi yang akan menerima surat pengumuman pemenang di kotak masuk.': 'Only the highest bidder will receive the winner announcement letter in the inbox.',
    'Tanggal & Waktu Penutupan Bid (Close Bid Date & Time)': 'Close Bid Date & Time',
    'Kosongkan jika lelang tidak memiliki batas waktu penutupan otomatis.': 'Leave blank if the auction does not have an automatic closing time limit.',
    'Tanggal Penutupan Bid': 'Bid Closing Date',
    'Maaf, lelang untuk unit ini sudah ditutup karena telah melewati batas waktu penutupan.': 'Sorry, the auction for this unit has been closed because it has passed the closing time limit.',
    'Lelang Ditutup': 'Auction Closed',
    'Lelang untuk unit ini telah resmi ditutup pada': 'The auction for this unit has been officially closed on',
    'Batas Waktu Bidding': 'Bidding Deadline',
    'Lelang ini akan ditutup secara otomatis pada': 'This auction will be closed automatically on',
    'Penawaran untuk unit ini telah ditutup karena melewati batas waktu penutupan lelang.': 'Bidding for this unit has been closed because it has passed the auction closing deadline.',
    'Sisa Waktu': 'Time Remaining',
    'Hari': 'Days',
    'Jam': 'Hours',
    'Menit': 'Mins',
    'Detik': 'Secs',
    'Close Bid': 'Close Bid',
    'Lupa Password?': 'Forgot Password?',
    'Reset Password': 'Reset Password',
    'Masukkan Email Anda': 'Enter Your Email',
    'Email tidak terdaftar atau salah.': 'Email is not registered or incorrect.',
    'OTP reset password telah dikirim ke email Anda.': 'Password reset OTP has been sent to your email.',
    'Masukkan Kode OTP & Password Baru': 'Enter OTP Code & New Password',
    'Kode OTP': 'OTP Code',
    'Password Baru': 'New Password',
    'Konfirmasi Password Baru': 'Confirm New Password',
    'Password berhasil direset! Silakan login kembali.': 'Password successfully reset! Please log in again.',
    'Password minimal 6 karakter.': 'Password must be at least 6 characters.',
    'Password tidak cocok.': 'Passwords do not match.',
    'Kode OTP salah atau tidak cocok.': 'OTP code is incorrect or does not match.',
    'Kirim OTP': 'Send OTP',
    'Verifikasi & Reset': 'Verify & Reset',
    'Reset Password Berhasil': 'Reset Password Success',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    const translationSet = translations[language];
    let text = translationSet[key] || translations['id'][key] || key;

    if (variables) {
      Object.entries(variables).forEach(([vKey, vVal]) => {
        text = text.replace(`{${vKey}}`, String(vVal));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
